-- ============================================================
-- Remove old Vendetta and Mark of Blood core script registrations
-- ============================================================
DELETE FROM `spell_script_names` WHERE `spell_id` IN (-49015, 50154) AND `ScriptName` = 'spell_dk_vendetta';
DELETE FROM `spell_script_names` WHERE `spell_id` = 49005 AND `ScriptName` = 'spell_dk_mark_of_blood';

-- ============================================================
-- Runic Power Mastery aura proc
-- ============================================================
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_dk_runic_power_mastery';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
    (-49455, 'spell_dk_runic_power_mastery');

-- ============================================================
-- Improved Rune Tap AfterCast buff
-- ============================================================
-- Generated by gen_sql.py on 2026-03-31

DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_dk_improved_rune_tap_buff';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
    (-48982, 'spell_dk_improved_rune_tap_buff');


-- ============================================================
-- Bloody Lesions Blood Boil AfterHit
-- ============================================================
-- Generated by gen_sql.py on 2026-03-31

DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_dk_bloody_lesions';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
    (-48721, 'spell_dk_bloody_lesions');


-- ============================================================
-- Mark of Blood rework (replaces core)
-- ============================================================
-- Generated by gen_sql.py on 2026-03-31

DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_dk_mark_of_blood_rework';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
    (49005, 'spell_dk_mark_of_blood_rework');


-- ============================================================
-- Will of the Necropolis Heart Strike parry stacks
-- ============================================================
-- Generated by gen_sql.py on 2026-03-31

DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_dk_will_of_necropolis_parry';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
    (-55050, 'spell_dk_will_of_necropolis_parry');


-- ============================================================
-- Presence improvements (Blood retained healing)
-- ============================================================
-- Generated by gen_sql.py on 2026-03-31

DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_dk_presence_blood_retained';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
    (48266, 'spell_dk_presence_blood_retained'),
    (48263, 'spell_dk_presence_blood_retained'),
    (48265, 'spell_dk_presence_blood_retained');

-- ============================================================
-- spell_proc: Mark of Blood parry detection
-- ProcFlags=4 (PROC_FLAG_SUCCESSFUL_MELEE_HIT from marked enemy)
-- HitMask=32 (PROC_HIT_PARRY - only when DK parries)
-- ============================================================
DELETE FROM `spell_proc` WHERE `SpellId` = 49005;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
    (49005, 0, 0, 0, 0, 0, 4, 0, 0, 32, 0, 0, 0, 100, 0, 0);
