-- Recoloured icons for the 16 gear upgrade tools.
--
-- Generated by tools/gen_upgrade_icons.py -- do not hand-edit; edit RAMP
-- there and regenerate, or the SQL and the art in
-- Interface/custom/Icons/ drift apart.
--
-- The tools shared displayid 6533 (INV_Potion_07, an NPC prop off item
-- 12870 'Monster - Item, Potion Red Offhand'), so all sixteen looked
-- like the same red potion.  Each now gets a display row of its own
-- pointing at Interface\Icons\woa_upgrade_<level>.blp, packed into
-- patch-4.mpq.  Retail's ItemDisplayInfo ends at 68742, so 69000+ is free.

-- -- display rows -----------------------------------------------------
-- Read by the server (DBCStores.cpp) and patched into the client's
-- ItemDisplayInfo.dbc by modules/world_of_alonecraft/dbc/build_dbc.py.
-- Model fields are left empty on purpose: cloning 6533's int fields
-- would carry Misc_1H_Potion_B_01.mdx along with them.
DELETE FROM `itemdisplayinfo_dbc` WHERE `ID` IN (69000, 69001, 69002, 69003, 69004, 69005, 69006, 69007, 69008, 69009, 69010, 69011, 69012, 69013, 69014, 69015);
INSERT INTO `itemdisplayinfo_dbc`
  (`ID`, `ModelName_1`, `ModelName_2`, `ModelTexture_1`, `ModelTexture_2`, `InventoryIcon_1`, `InventoryIcon_2`, `GeosetGroup_1`, `GeosetGroup_2`, `GeosetGroup_3`, `Flags`, `SpellVisualID`, `GroupSoundIndex`, `HelmetGeosetVis_1`, `HelmetGeosetVis_2`, `Texture_1`, `Texture_2`, `Texture_3`, `Texture_4`, `Texture_5`, `Texture_6`, `Texture_7`, `Texture_8`, `ItemVisual`, `ParticleColorID`)
VALUES
(69000, '', '', '', '', 'woa_upgrade_5', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69001, '', '', '', '', 'woa_upgrade_10', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69002, '', '', '', '', 'woa_upgrade_15', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69003, '', '', '', '', 'woa_upgrade_20', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69004, '', '', '', '', 'woa_upgrade_25', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69005, '', '', '', '', 'woa_upgrade_30', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69006, '', '', '', '', 'woa_upgrade_35', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69007, '', '', '', '', 'woa_upgrade_40', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69008, '', '', '', '', 'woa_upgrade_45', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69009, '', '', '', '', 'woa_upgrade_50', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69010, '', '', '', '', 'woa_upgrade_55', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69011, '', '', '', '', 'woa_upgrade_60', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69012, '', '', '', '', 'woa_upgrade_65', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69013, '', '', '', '', 'woa_upgrade_70', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69014, '', '', '', '', 'woa_upgrade_75', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0),
(69015, '', '', '', '', 'woa_upgrade_80', '', 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', 0, 0);

-- -- point the tools at them ------------------------------------------
-- UPDATE, not a full-row re-INSERT: these rows already carry
-- RequiredLevel from woa_2026_08_06_17.sql and prices from
-- woa_2026_08_06_24.sql, and a re-INSERT would revert both.
UPDATE `item_template` SET `displayid` = 69000 WHERE `entry` = 200100;
UPDATE `item_template` SET `displayid` = 69001 WHERE `entry` = 200101;
UPDATE `item_template` SET `displayid` = 69002 WHERE `entry` = 200102;
UPDATE `item_template` SET `displayid` = 69003 WHERE `entry` = 200103;
UPDATE `item_template` SET `displayid` = 69004 WHERE `entry` = 200104;
UPDATE `item_template` SET `displayid` = 69005 WHERE `entry` = 200105;
UPDATE `item_template` SET `displayid` = 69006 WHERE `entry` = 200106;
UPDATE `item_template` SET `displayid` = 69007 WHERE `entry` = 200107;
UPDATE `item_template` SET `displayid` = 69008 WHERE `entry` = 200108;
UPDATE `item_template` SET `displayid` = 69009 WHERE `entry` = 200109;
UPDATE `item_template` SET `displayid` = 69010 WHERE `entry` = 200110;
UPDATE `item_template` SET `displayid` = 69011 WHERE `entry` = 200111;
UPDATE `item_template` SET `displayid` = 69012 WHERE `entry` = 200112;
UPDATE `item_template` SET `displayid` = 69013 WHERE `entry` = 200113;
UPDATE `item_template` SET `displayid` = 69014 WHERE `entry` = 200114;
UPDATE `item_template` SET `displayid` = 69015 WHERE `entry` = 200115;

UPDATE `item_dbc` SET `DisplayInfoID` = 69000 WHERE `ID` = 200100;
UPDATE `item_dbc` SET `DisplayInfoID` = 69001 WHERE `ID` = 200101;
UPDATE `item_dbc` SET `DisplayInfoID` = 69002 WHERE `ID` = 200102;
UPDATE `item_dbc` SET `DisplayInfoID` = 69003 WHERE `ID` = 200103;
UPDATE `item_dbc` SET `DisplayInfoID` = 69004 WHERE `ID` = 200104;
UPDATE `item_dbc` SET `DisplayInfoID` = 69005 WHERE `ID` = 200105;
UPDATE `item_dbc` SET `DisplayInfoID` = 69006 WHERE `ID` = 200106;
UPDATE `item_dbc` SET `DisplayInfoID` = 69007 WHERE `ID` = 200107;
UPDATE `item_dbc` SET `DisplayInfoID` = 69008 WHERE `ID` = 200108;
UPDATE `item_dbc` SET `DisplayInfoID` = 69009 WHERE `ID` = 200109;
UPDATE `item_dbc` SET `DisplayInfoID` = 69010 WHERE `ID` = 200110;
UPDATE `item_dbc` SET `DisplayInfoID` = 69011 WHERE `ID` = 200111;
UPDATE `item_dbc` SET `DisplayInfoID` = 69012 WHERE `ID` = 200112;
UPDATE `item_dbc` SET `DisplayInfoID` = 69013 WHERE `ID` = 200113;
UPDATE `item_dbc` SET `DisplayInfoID` = 69014 WHERE `ID` = 200114;
UPDATE `item_dbc` SET `DisplayInfoID` = 69015 WHERE `ID` = 200115;
