-- ==========================================================================
-- Item Upgrade Vendor NPC
-- ==========================================================================
--
-- Swaps an equipped item for the next 5-level variant of itself, for gold.
-- Variant items themselves are generated by tools/gen_item_variants.py.
--
-- Entry 200011: 200000-200009 are taken (Alonecraft guardians/conduits, plus
-- mod-mythic-plus squatting on 200005 and 200007), so this starts above them.
-- Spawn guids 8000041-8000051: the next free block after mod-mythic-plus's
-- 8000021-8000031, following its convention of ~20-wide blocks from 8000000.

SET @Entry  := 200011;
SET @Name   := 'Artificer Volen';
SET @Title  := 'Item Upgrades';
SET @Model  := 19646;  -- ethereal, matching the other Alonecraft service NPCs

DELETE FROM `creature` WHERE `id` = @Entry;
DELETE FROM `creature_template_model` WHERE `CreatureID` = @Entry;
DELETE FROM `creature_template` WHERE `entry` = @Entry;

INSERT INTO `creature_template` (
    `entry`, `name`, `subname`, `minlevel`, `maxlevel`, `faction`, `npcflag`,
    `speed_walk`, `speed_run`, `unit_class`, `unit_flags`, `type`, `flags_extra`,
    `ScriptName`
) VALUES (
    @Entry, @Name, @Title, 80, 80,
    35,          -- friendly to both factions
    128,         -- UNIT_NPC_FLAG_VENDOR
    1, 1.14286,
    1,           -- warrior
    2,           -- UNIT_FLAG_NON_ATTACKABLE
    7,           -- humanoid
    2,           -- CREATURE_FLAG_EXTRA_CIVILIAN
    ''           -- no script: the shop is plain npc_vendor data
);

-- Volen was a gossip NPC running npc_item_upgrade_vendor when this file was
-- written.  That script has since been deleted in favour of the item-targeted
-- tools, and woa_2026_08_06_10.sql UPDATEs this row to npcflag 128 with no
-- script -- but 10 sorts BEFORE 11, so the full-row INSERT below reverted it
-- every apply and Volen offered an empty gossip window instead of a shop.
-- Fixed at the source rather than with a 15th file, so a fresh database is
-- correct on the first pass.

INSERT INTO `creature_template_model`
    (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`)
VALUES
    (@Entry, 0, @Model, 1, 1);

-- City spawns, coordinates from mod-mythic-plus's ethereal NPC set.
INSERT INTO `creature` (
    `guid`, `id`, `map`, `spawnMask`, `phaseMask`,
    `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`
) VALUES
-- ALLIANCE
(8000041, @Entry, 0,   1, 1,  -8842.0,  626.0,   94.30,   0.44, 180),   -- Stormwind
(8000042, @Entry, 0,   1, 1,  -4918.0,  -957.0,  501.53,  2.26, 180),   -- Ironforge
(8000043, @Entry, 1,   1, 1,   9873.0,  2494.0,  1316.20, 3.10, 180),   -- Darnassus
(8000044, @Entry, 530, 1, 1,  -3862.7,  -11645.8, -137.63, 2.38, 180),  -- Exodar
-- HORDE
(8000045, @Entry, 1,   1, 1,   1680.0,  -4316.0, 61.80,   5.70, 180),   -- Orgrimmar
(8000046, @Entry, 1,   1, 1,  -1277.6,  73.0,    128.75,  5.96, 180),   -- Thunder Bluff
(8000047, @Entry, 0,   1, 1,   1641.2,  240.1,   -43.10,  3.14, 180),   -- Undercity
(8000048, @Entry, 530, 1, 1,   9742.0,  -7454.0, 13.56,   0.50, 180),   -- Silvermoon
-- NEUTRAL
(8000049, @Entry, 530, 1, 1,  -1850.0,  5436.0,  -12.10,  5.50, 180),   -- Shattrath
(8000050, @Entry, 571, 1, 1,   5811.0,  506.2,   657.58,  5.54, 180),   -- Dalaran
(8000051, @Entry, 0,   1, 1,  -14406.0, 420.0,   23.70,   4.00, 180);   -- Booty Bay
