-- ============================================================
-- Marksmanship: Piercing Shots
-- ============================================================
--
-- TODO.md: "Critical Aimed, Steady and Chimera Shots bleed the target for 30%
--  of the damage dealt over 8 sec and have a 33/66/100% chance to reset the
--  duration of Lacerating Shot on your target, and increase the duration of
--  Lacerating Shot by 2/4/6 sec (3 ranks)"
--
-- The bleed half already works on this core and is left alone: core's
-- spell_hun_piercing_shots (spell_hunter.cpp:1622) reads aurEff->GetAmount()
-- and feeds CastDelayedSpellWithPeriodicAmount, so flattening 10/20/30% to a
-- flat 30% is one column -- EffectBasePoints1 29 on all three ranks.  63468 is
-- already 8s with 1s ticks; no change there either.
--
-- The refresh half is a second AuraScript on the same spell ids.  See the
-- spell_proc block below for the constraint that shapes it, and for the
-- Chance = 100 that stops this change quietly nerfing the bleed.
--
-- The duration half is Effect2, a plain SPELLMOD_DURATION, and it is the same
-- shape as Lethal Instincts extending Instinctive Fire: a spellmod applies to
-- every application of Lacerating Shot, including casts that never proc this
-- talent, which is what the script path cannot do.  Base points 1999/3999/5999
-- because a flat modifier's value is BasePoints + max(1, DieSides), and
-- $/1000;s2 renders that same total as 2 / 4 / 6.
--
-- NOTE THIS IS A DAMAGE INCREASE, not just uptime.  Lacerating Shot is
-- DurationIndex 1 (10000 ms) with EffectAmplitude1 2000, so it ticks 5 times;
-- an aura's tick count is its max duration divided by the amplitude, computed
-- at creation.  +2/4/6 sec therefore buys 6/7/8 ticks, and because the per-tick
-- amount is a fixed 3.6% of ranged attack power, total bleed damage rises
-- 20/40/60%.  Chosen deliberately gentler than Lethal Instincts' +50/100%, and
-- the whole knob is EffectBasePoints2 on three rows if it wants retuning.
--
-- The refresh and the extension compose correctly: Aura::RefreshDuration resets
-- to GetMaxDuration(), which already includes the modifier because
-- Aura::CalcMaxDuration (SpellAuras.cpp:806) applied it when the aura was made.
--
-- One cosmetic limit: Lacerating Shot's own description says "over $d", and $d
-- is resolved client-side from the base DurationIndex.  The client cannot know
-- about a server-side spellmod, so that line keeps reading 10 sec.  The tooltip
-- is per-tick ("every $t1 seconds") and stays accurate.



-- ============================================================
-- Piercing Shots -- flat 30% bleed, 33% Lacerating Shot refresh, +2s Lacerating Shot
-- ============================================================
-- Generated by gen_sql.py on 2026-08-12
-- Overrides: EffectBasePoints1: 29 -> 29, ProcChance: 33 -> 33, Effect2: 0 -> 6, EffectApplyAuraName2: 0 -> 107, EffectMiscValue2: 0 -> 1, EffectBasePoints2: 0 -> 1999, EffectDieSides2: 0 -> 1, EffectImplicitTargetA2: 0 -> 1, EffectSpellClassMaskB3: 0 -> 8388608, SpellDescription0: 'Your critical Aimed, Steady and Chimera Shots cause the target to bleed for $s1% of the damage dealt over $63468d, and have a $h% chance to refresh the duration of your Lacerating Shot on the target.' -> 'Your critical Aimed, Steady and Chimera Shots bleed the target for $s1% of the damage dealt over $63468d and have a $h% chance to reset the duration of your Lacerating Shot on the target.  Increases the duration of your Lacerating Shot by $/1000;s2 sec.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 53234;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(53234, 0, 0, 0, 464, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 256, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 6, 0, 1, 1, 0, 0, 0, 0, 29, 1999, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 42, 107, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 131072, 1, 0, 8192, 0, 8388608, 0, 0, 0, 0, 0, 3247, 0, 0, 'Piercing Shots', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Rank 1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Your critical Aimed, Steady and Chimera Shots bleed the target for $s1% of the damage dealt over $63468d and have a $h% chance to reset the duration of your Lacerating Shot on the target.  Increases the duration of your Lacerating Shot by $/1000;s2 sec.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0);


-- ============================================================
-- Piercing Shots -- flat 30% bleed, 66% Lacerating Shot refresh, +4s Lacerating Shot
-- ============================================================
-- Generated by gen_sql.py on 2026-08-12
-- Overrides: EffectBasePoints1: 29 -> 29, ProcChance: 66 -> 66, Effect2: 0 -> 6, EffectApplyAuraName2: 0 -> 107, EffectMiscValue2: 0 -> 1, EffectBasePoints2: 0 -> 3999, EffectDieSides2: 0 -> 1, EffectImplicitTargetA2: 0 -> 1, EffectSpellClassMaskB3: 0 -> 8388608, SpellDescription0: 'Your critical Aimed, Steady and Chimera Shots cause the target to bleed for $s1% of the damage dealt over $63468d, and have a $h% chance to refresh the duration of your Lacerating Shot on the target.' -> 'Your critical Aimed, Steady and Chimera Shots bleed the target for $s1% of the damage dealt over $63468d and have a $h% chance to reset the duration of your Lacerating Shot on the target.  Increases the duration of your Lacerating Shot by $/1000;s2 sec.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 53237;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(53237, 0, 0, 0, 464, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 256, 66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 6, 0, 1, 1, 0, 0, 0, 0, 29, 3999, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 42, 107, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 131072, 1, 0, 8192, 0, 8388608, 0, 0, 0, 0, 0, 3247, 0, 0, 'Piercing Shots', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Rank 2', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Your critical Aimed, Steady and Chimera Shots bleed the target for $s1% of the damage dealt over $63468d and have a $h% chance to reset the duration of your Lacerating Shot on the target.  Increases the duration of your Lacerating Shot by $/1000;s2 sec.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0);


-- ============================================================
-- Piercing Shots -- flat 30% bleed, 100% Lacerating Shot refresh, +6s Lacerating Shot
-- ============================================================
-- Generated by gen_sql.py on 2026-08-12
-- Overrides: EffectBasePoints1: 29 -> 29, ProcChance: 100 -> 100, Effect2: 0 -> 6, EffectApplyAuraName2: 0 -> 107, EffectMiscValue2: 0 -> 1, EffectBasePoints2: 0 -> 5999, EffectDieSides2: 0 -> 1, EffectImplicitTargetA2: 0 -> 1, EffectSpellClassMaskB3: 0 -> 8388608, SpellDescription0: 'Your critical Aimed, Steady and Chimera Shots cause the target to bleed for $s1% of the damage dealt over $63468d, and have a $h% chance to refresh the duration of your Lacerating Shot on the target.' -> 'Your critical Aimed, Steady and Chimera Shots bleed the target for $s1% of the damage dealt over $63468d and have a $h% chance to reset the duration of your Lacerating Shot on the target.  Increases the duration of your Lacerating Shot by $/1000;s2 sec.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 53238;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(53238, 0, 0, 0, 464, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 256, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 6, 0, 1, 1, 0, 0, 0, 0, 29, 5999, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 42, 107, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 131072, 1, 0, 8192, 0, 8388608, 0, 0, 0, 0, 0, 3247, 0, 0, 'Piercing Shots', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Rank 3', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Your critical Aimed, Steady and Chimera Shots bleed the target for $s1% of the damage dealt over $63468d and have a $h% chance to reset the duration of your Lacerating Shot on the target.  Increases the duration of your Lacerating Shot by $/1000;s2 sec.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0);

-- ============================================================
-- Lacerating Shot needs a family flag to be modifiable
-- ============================================================
--
-- Same trap as Instinctive Fire's buff, one talent along: without this the
-- +2/4/6 sec above silently does NOTHING and nothing logs.
-- Player::IsAffectedBySpellMod requires `spellmod->mask & spellInfo->
-- SpellFamilyFlags` to be non-zero, and Lacerating Shot's three ranks were left
-- with SpellFamilyName 9 but all three flag words zero after their rework.
--
-- That zeroing is why spell_hun_taste_for_blood and
-- spell_hun_piercing_shots_lacerate both have to name the ranks explicitly
-- instead of matching a family mask.  Those scripts are unaffected by this
-- change -- they look the spell up by id -- so the bit is purely for the
-- modifier's benefit.
--
-- Bit 23 of word 2 (8388608).  Bits 21 and 22 are already taken by Instinctive
-- Fire and its buff; 23 was verified free by scanning every family-9 record in
-- Spell.dbc, as neither a flag nor a mask.  All three ranks share one bit, which
-- is how a rank chain normally works and what lets one mask cover all of them.
--
-- UPDATE, not a re-INSERT: the full rows live in woa_2026_08_11_02.sql, which
-- sorts earlier, so these land on top of them.

UPDATE `alonecraft_spell_dbc` SET `SpellFamilyFlags2` = 8388608 WHERE `ID` IN (1513, 14326, 14327);

-- ============================================================
-- Piercing Shots: proc chance, and the second script
-- ============================================================
--
-- THE Chance = 100 HERE IS THE WHOLE POINT OF THIS BLOCK.  Core's row ships
-- Chance = 0, which makes Aura::CalcProcChance fall back to the DBC ProcChance
-- (SpellMgr.cpp:2083).  Since the DBC ProcChance above is now 33/66/100 -- it
-- has to be, because $h in the description reads it -- leaving the row at 0
-- would silently drop the BLEED to a 33% chance at rank 1.  The two numbers are
-- deliberately different things: the bleed always happens, the refresh is the
-- part that rolls.
--
-- Everything else on the row is core's, restated so the whole thing is visible
-- in one place: family 9, masks 131072/1/1 (Aimed / Steady / Chimera),
-- SpellPhaseMask 2, HitMask 2 (PROC_HIT_CRITICAL).

DELETE FROM `spell_proc` WHERE `SpellId` = -53234;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(-53234, 0, 9, 131072, 1, 1, 0, 0, 2, 2, 0, 0, 0, 100, 0, 0);

-- ADDED ALONGSIDE core's spell_hun_piercing_shots, not instead of it.  The
-- bleed is already correct in core (spell_hunter.cpp:1622) and only its
-- percentage changed, which is the DBC edit above.
--
-- _spellScriptsStore is a multimap (ObjectMgr.h:390) and
-- Aura::CallScriptEffectProcHandlers iterates every loaded script
-- (SpellAuras.cpp:2723), so both run.  The new script therefore must NOT
-- register DoCheckProc and must NOT call PreventDefaultAction:
-- CallScriptCheckProcHandlers ANDs results across scripts (SpellAuras.cpp:2625)
-- and prevention is global, so either one would silently kill core's bleed.

DELETE FROM `spell_script_names` WHERE `spell_id` = -53234 AND `ScriptName` = 'spell_hun_piercing_shots_lacerate';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(-53234, 'spell_hun_piercing_shots_lacerate');
