-- ===========================================================================
-- Warlock: Infernal Bargain collapsed to a single rank
-- ===========================================================================
--
-- Following the same collapse Sacrifice the Weak got in
-- woa_2026_08_03_02.sql and Dirty Tricks in woa_2026_08_03_07.sql: one
-- talent point now buys the finished ability.
--
-- WHICH TUNING SURVIVES
--
--   The three ranks differed only in two data points -- the rank buff in
--   EffectTriggerSpell1 (200401 / 200404 / 200405, carrying 2/3/4% damage
--   and 1/1/2% crit per shard) and the channel's own damage reduction in
--   EffectBasePoints2 (-16 / -21 / -26, i.e. 15/20/25%).
--
--   63349 keeps rank 3's numbers: buff 200405, EffectBasePoints2 -26.  A
--   single point is the whole talent, so it delivers the whole effect --
--   the same reading Sacrifice the Weak and Dirty Tricks were collapsed
--   under.  To make the single rank the WEAKEST version instead, point
--   EffectTriggerSpell1 back at 200401 and set EffectBasePoints2 to -16.
--
-- WHAT DOES NOT CHANGE
--
--   * spell_script_names registers -63349 (all ranks), so the C++ binding
--     survives losing ranks 2 and 3 untouched.
--   * spell_warl_infernal_bargain reads the buff id out of
--     EffectTriggerSpell1 rather than switching on rank, so retargeting
--     63349 at 200405 is the entire change it sees.
--   * No talent lists 1887 as a prerequisite (checked across all 895
--     Talent.dbc records), so shortening it cannot orphan an arrow.
--   * Talent slot (TabID 301, tier 5, column 2) and Flags = 1
--     (addToSpellBook, see woa_2026_08_03_11.sql) are unchanged.
--
--   NOTE: a character that had already spent points on rank 2 or 3 keeps
--   the now-orphaned spell in its spellbook until the next talent reset.
--
-- ===========================================================================


-- ============================================================
-- Infernal Bargain: single rank, carrying the old rank 3 tuning
-- ============================================================
-- Generated by gen_sql.py on 2026-08-03
-- Overrides: EffectBasePoints2: -16 -> -26, EffectTriggerSpell1: 200401 -> 200405, SpellRank0: 'Rank 1' -> '', SpellDescription0: 'Channel the souls you carry into the endless void, consuming one Soul Shard every 1 sec for $d. Each shard consumed increases your damage by $200401s1% and your spell critical strike chance by $200401s2% for $200401d, stacking up to 4 times. While channeling you take 15% less damage.' -> 'Channel the souls you carry into the endless void, consuming one Soul Shard every 1 sec for $d. Each shard consumed increases your damage by $200405s1% and your spell critical strike chance by $200405s2% for $200405d, stacking up to 4 times. While channeling you take 25% less damage.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 63349;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(63349, 0, 0, 0, 272, 64, 0, 524288, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 120000, 0, 1, 0, 3084, 0, 101, 0, 0, 0, 1, 35, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 6, 0, 0, 1, 0, 0, 0, 0, 0, -26, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 226, 87, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 127, 0, 0, 0, 0, 200405, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2307, 0, 50, 'Infernal Bargain', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Channel the souls you carry into the endless void, consuming one Soul Shard every 1 sec for $d. Each shard consumed increases your damage by $200405s1% and your spell critical strike chance by $200405s2% for $200405d, stacking up to 4 times. While channeling you take 25% less damage.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);

-- ============================================================
-- talent_dbc: single rank
--   Columns: ID, TabID, TierID, ColumnIndex, SpellRank_1-9,
--            PrereqTalent_1-3, PrereqRank_1-3, Flags, RequiredSpellID,
--            CategoryMask_1-2
--   1887 = Infernal Bargain (was Molten Skin), Destruction (301),
--   tier 5, column 2.  Flags = 1 keeps it in the spellbook.
-- ============================================================
DELETE FROM `talent_dbc` WHERE `ID` = 1887;
INSERT INTO `talent_dbc` (`ID`, `TabID`, `TierID`, `ColumnIndex`, `SpellRank_1`, `SpellRank_2`, `SpellRank_3`, `SpellRank_4`, `SpellRank_5`, `SpellRank_6`, `SpellRank_7`, `SpellRank_8`, `SpellRank_9`, `PrereqTalent_1`, `PrereqTalent_2`, `PrereqTalent_3`, `PrereqRank_1`, `PrereqRank_2`, `PrereqRank_3`, `Flags`, `RequiredSpellID`, `CategoryMask_1`, `CategoryMask_2`) VALUES
(1887, 301, 5, 2, 63349, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0);

-- ============================================================
-- Drop the now-unreachable rank 2 and 3 overrides, so 63350 and 63351
-- revert to the untouched Blizzard Molten Skin ranks.  Nothing lists
-- them once the talent carries only SpellRank_1.
-- ============================================================
DELETE FROM `alonecraft_spell_dbc` WHERE `ID` IN (63350, 63351);

-- ============================================================
-- Drop the orphaned rank 1 and rank 2 buffs.  200401 and 200404 exist
-- only as alonecraft_spell_dbc rows (custom 200000+ ids), and 63349 is
-- now the only spell that ever pointed at them.
-- ============================================================
DELETE FROM `alonecraft_spell_dbc` WHERE `ID` IN (200401, 200404);

-- ============================================================
-- 200405 is the only Infernal Bargain buff left, so its "Rank 3"
-- subtext no longer means anything.  A single-column UPDATE is
-- idempotent; 200405 is custom, so gen_sql.py cannot regenerate its row
-- from Spell.dbc.
-- ============================================================
UPDATE `alonecraft_spell_dbc` SET `SpellRank0` = '' WHERE `ID` = 200405;
