-- ===========================================================================
-- Warlock / Demonology: Metamorphosis becomes a shard-fuelled stance
-- ===========================================================================
--
-- Seventh and last file of the Demonology batch.  Kept on its own because it
-- is the most player-visible change in the batch and the most likely to be
-- retuned or reverted independently of everything else.
--
-- No cooldown, no fixed duration.  Entering costs one Soul Shard and the form
-- burns one more every 6 seconds, dropping automatically when the warlock runs
-- out.  All defensive benefit is removed -- that now belongs to Demonic Aegis.
--
-- CHANGES TO 47241
--
--   RecoveryTime   180000 -> 0       no cooldown; re-entry is limited by
--                                    shards alone.
--   DurationIndex       9 -> 21      30000 ms -> -1 (permanent).  Index values
--                                    read from SpellDuration.dbc.
--   Effect2        MOD_BASE_RESISTANCE_PCT (142), BasePoints 599  ->
--                  SPELL_AURA_PERIODIC_DUMMY (226), EffectAmplitude2 6000,
--                  BasePoints 0, MiscValue 0.
--
--   That single effect swap does both jobs at once: it deletes the +600% base
--   armor (moved to Demonic Aegis in file 03) and creates the 6-second upkeep
--   heartbeat the script listens on.  No custom spell id was needed, which is
--   why the batch stops at 200424.
--
-- DELIBERATELY UNCHANGED
--
--   Effect1  MOD_SHAPESHIFT, form 22        -- the form itself
--   Effect3  MOD_DAMAGE_PERCENT_DONE +20%   -- the offensive payoff
--   In-form kit: 50589 Immolation Aura, 54785 Demon Charge,
--                59671 Challenging Howl, 50581 Shadow Cleave.
--
--   Note 50589 stays exactly as it is.  The Felguard's version from Imperious
--   Flames is a separate clone (200407), so tuning one never moves the other.
--
--   Attributes stay at 16.  That is SPELL_ATTR0_IS_ABILITY, NOT the
--   cancel-blocking bit -- SPELL_ATTR0_NO_AURA_CANCEL is 0x80000000
--   (SharedDefines.h:401) and is not set, so the player can still right-click
--   the buff off.  No SpellShapeshiftForm.dbc change is needed either: form 22
--   is already stance-like and permits normal casting.
--
--   No reagent is declared.  Doing the shard accounting in C++ keeps the entry
--   cost and the 6-second upkeep on one code path.
--


-- ============================================================
-- Metamorphosis: no cooldown, no duration, Soul Shard upkeep, no defensive bonus
-- ============================================================
-- Generated by gen_sql.py on 2026-08-02
-- Overrides: RecoveryTime: 180000 -> 0, DurationIndex: 9 -> 21, EffectApplyAuraName2: 142 -> 226, EffectAmplitude2: 0 -> 6000, EffectBasePoints2: 599 -> 0, EffectDieSides2: 1 -> 0, EffectMiscValue2: 1 -> 0, EffectSpellClassMaskB1: 0 -> 0, EffectSpellClassMaskB2: 16384 -> 0, EffectSpellClassMaskB3: 0 -> 0, SpellDescription0: 'You transform into a Demon for $47241d.  This form increases your armor contribution from items by $47241s2%, damage by $47241s3%, reduces the chance you'll be critically hit by melee attacks by $54879s1% and reduces the duration of stun and snare effects by $54817s1%.  You gain some unique demon abilities in addition to your normal abilities.' -> 'Transform into a Demon, increasing your damage done by 20%.  Costs a Soul Shard to enter and another every 6 sec; the form fades when you have no Soul Shards left.', SpellToolTip0: 'Demon Form.
--   Armor contribution from items increased by $47241s2%.
--   Chance to be critically hit by melee reduced by 6%.
--   Damage increased by $47241s3%.
--   Stun and snare duration reduced by $54817s1%.' -> 'Demon Form.
--   Damage increased by $47241s3%.
--   Consumes a Soul Shard every 6 sec.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 47241;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(47241, 0, 0, 0, 16, 131072, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 101, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 6, 6, 1, 0, 1, 0, 0, 0, -1, 0, 19, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 36, 226, 79, 0, 6000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 0, 127, 0, 0, 0, 0, 0, 0, 0, 0, 0, 67108864, 0, 0, 0, 0, 0, 0, 0, 0, 12118, 0, 3314, 0, 0, 'Metamorphosis', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, 'Transform into a Demon, increasing your damage done by 20%.  Costs a Soul Shard to enter and another every 6 sec; the form fades when you have no Soul Shards left.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Demon Form.
Damage increased by $47241s3%.
Consumes a Soul Shard every 6 sec.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 0, 0, 0, 0, 5, 0, 0, 8192, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0);
