

-- ============================================================
-- Molten Rain R1: allow proc from Rain of Fire's triggered damage spell 42223 (PROC_ATTR_TRIGGERED_CAN_PROC)
-- ============================================================
-- Generated by gen_sql.py on 2026-08-03

DELETE FROM `spell_proc` WHERE `SpellId` = 18126;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(18126, 0, 5, 32, 0, 0, 65536, 1, 2, 0, 2, 0, 0, 8, 0, 0);


-- ============================================================
-- Molten Rain R2: same
-- ============================================================
-- Generated by gen_sql.py on 2026-08-03

DELETE FROM `spell_proc` WHERE `SpellId` = 18127;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(18127, 0, 5, 32, 0, 0, 65536, 1, 2, 0, 2, 0, 0, 15, 0, 0);
