-- ============================================================
-- Alonecraft 4.61 -- Rogue / Subtlety
--   Dirty Tricks -> Ambush and Backstab drop the behind-target rule,
--                   collapsed to a single talent point
-- ============================================================
--
-- TODO.md:
--   "Dirty Tricks: Redesigned. Ambush and Backstab no longer require you to
--    be behind the target."
--
--
-- WHY THIS CANNOT BE DONE IN SQL ALONE
--
--   The requirement is SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET, and it is
--   not a DBC field.  SpellMgr.cpp:3531-3591 sets it from a hard-coded
--   switch listing every Backstab and Ambush rank, and Spell.cpp:5870
--   rejects the cast with SPELL_FAILED_NOT_BEHIND.  Nothing in
--   alonecraft_spell_dbc can reach it.
--
--   It is also a per-SpellInfo global rather than a per-player one, so
--   simply clearing it would hand the change to every rogue on the server
--   whether or not they spent the point.
--
--   RogueDirtyTricks.cpp therefore does it in two halves, both inside the
--   module: a GlobalScript on GLOBALHOOK_ON_LOAD_SPELL_CUSTOM_ATTR clears
--   the attribute (that hook runs at SpellMgr.cpp:3845, after the switch),
--   and a SpellScript on all Ambush and Backstab ranks puts the failure
--   back for anyone without the talent.  No core file is touched.
--
--
-- ONE RANK, NOT TWO
--
--   The redesign is binary -- either the requirement is gone or it is not
--   -- so a second rank has nothing to buy.  Following the same collapse
--   Sacrifice the Weak got in woa_2026_08_03_02.sql:
--
--     * talent_dbc 262 keeps SpellRank_1 = 14076 only; SpellRank_2 cleared.
--     * The alonecraft_spell_dbc override for 14094 is dropped, so that ID
--       reverts to the untouched Blizzard Dirty Tricks rank 2.  It is
--       unreachable once the talent no longer lists it.
--     * 14076 loses its "Rank 1" subtext, since there is only one.
--
--   Nothing in Talent.dbc lists talent 262 as a prerequisite, so shortening
--   it cannot orphan an arrow elsewhere in the tree (checked across all
--   895 talent records).
--
--   NOTE: a character that had already spent a point on rank 2 keeps the
--   now-orphaned spell in its spellbook until the next talent reset.
--
--
-- THE TALENT SPELL (14076)
--
--   The old effects -- Blind/Sap range and energy cost -- are dropped, per
--   "Redesigned".  Effect1 becomes SPELL_AURA_DUMMY so the talent still
--   applies an aura the script can test with HasAura(); a talent whose
--   effects are all zeroed applies nothing and would be undetectable.
--
--   Effect 1's class mask is zeroed.  It selected Blind and Sap for the old
--   spell modifier, and a dummy must not carry a mask.
--
-- ============================================================


-- ============================================================
-- Dirty Tricks -- single rank
-- ============================================================
-- Generated by gen_sql.py on 2026-08-03
-- Overrides: EffectApplyAuraName1: 107 -> 4, EffectBasePoints1: 1 -> 0, EffectDieSides1: 1 -> 0, EffectMiscValue1: 5 -> 0, EffectSpellClassMaskA1: 16777344 -> 0, EffectSpellClassMaskA2: 0 -> 0, EffectSpellClassMaskA3: 0 -> 0, Effect2: 6 -> 0, EffectApplyAuraName2: 108 -> 0, EffectBasePoints2: -26 -> 0, EffectDieSides2: 1 -> 0, EffectMiscValue2: 14 -> 0, EffectSpellClassMaskB1: 16777344 -> 0, EffectSpellClassMaskB2: 0 -> 0, EffectSpellClassMaskB3: 0 -> 0, SpellRank0: 'Rank 1' -> '', SpellDescription0: 'Increases the range of your Blind and Sap abilities by $s1 yards and reduces the energy cost of your Blind and Sap abilities by $s2%.' -> 'Your Ambush and Backstab no longer require you to be behind the target.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 14076;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(14076, 0, 0, 0, 464, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 101, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 249, 0, 0, 'Dirty Tricks', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Your Ambush and Backstab no longer require you to be behind the target.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0);

-- ============================================================
-- talent_dbc: single rank
--   Columns: ID, TabID, TierID, ColumnIndex, SpellRank_1-9,
--            PrereqTalent_1-3, PrereqRank_1-3, Flags, RequiredSpellID,
--            CategoryMask_1-2
--   262 = Dirty Tricks, Subtlety (183), tier 1, column 1.
-- ============================================================
DELETE FROM `talent_dbc` WHERE `ID` = 262;
INSERT INTO `talent_dbc` (`ID`, `TabID`, `TierID`, `ColumnIndex`, `SpellRank_1`, `SpellRank_2`, `SpellRank_3`, `SpellRank_4`, `SpellRank_5`, `SpellRank_6`, `SpellRank_7`, `SpellRank_8`, `SpellRank_9`, `PrereqTalent_1`, `PrereqTalent_2`, `PrereqTalent_3`, `PrereqRank_1`, `PrereqRank_2`, `PrereqRank_3`, `Flags`, `RequiredSpellID`, `CategoryMask_1`, `CategoryMask_2`) VALUES
(262, 183, 1, 1, 14076, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

-- ============================================================
-- Drop the now-unused rank 2 override so 14094 reverts to vanilla
-- ============================================================
DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 14094;

-- ============================================================
-- Script registration
--   Negative IDs = all ranks.  53 = Backstab rank 1, 8676 = Ambush rank 1.
-- ============================================================
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_rog_dirty_tricks';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(-53,   'spell_rog_dirty_tricks'),
(-8676, 'spell_rog_dirty_tricks');
