-- ============================================================
-- Warrior (Protection): Intervene becomes an enemy charge
-- ============================================================
-- Redesign of woa_2026_08_09_05.sql / _18.sql.  Intervene is now Protection's
-- Charge: you leap at an ENEMY, not at a party member.
--
-- Why the whole ability changes rather than just the target.  Charge is Battle
-- Stance only and Intercept is Berserker Stance only, so the one spec that is
-- required to stand in Defensive Stance had no gap closer at all -- a
-- Protection warrior who lost a target simply walked.  Intervene was the
-- obvious donor: it is already a SPELL_EFFECT_CHARGE, already Defensive Stance
-- only (Stances 131072), already on a 30 second cooldown, and its actual job --
-- soaking one attack aimed at somebody else -- is worth nothing on a solo fork.
--
-- Three things had to move, and the second and third are the ones that would
-- have silently misbehaved if only the target type were flipped:
--
-- 1. EffectImplicitTargetA on effects 1 and 3: 57 (TARGET_UNIT_TARGET_RAID) ->
--    6 (TARGET_UNIT_TARGET_ENEMY).  This is what Charge (100) and Intercept
--    (20252) both use.
--
-- 2. Effect2 is blanked.  It was SPELL_AURA_ADD_CASTER_HIT_TRIGGER at 100% --
--    "the next melee or ranged attack against this unit hits the warrior
--    instead".  Applied to an enemy that is not merely useless, it is
--    backwards: it would redirect the target's incoming attacks.
--
-- 3. AttributesEx5 loses 0x800 SPELL_ATTR5_IMPLIED_TARGETING ("auto-target
--    target of target", SharedDefines.h:566).  That is an ally-assist
--    convenience -- click your healer, hit their attacker.  Pointed at an
--    enemy it resolves to the enemy's target, which is usually the warrior
--    themselves.  Charge does not carry it.
--
--    AttributesEx6 swaps 0x4000000 for Charge's 0x800000
--    (SPELL_ATTR6_TAPS_IMMEDIATELY), so charging in tags the mob the way
--    Charge and Intercept do.
--
-- Deliberately NOT copied from Charge:
--
--   SPELL_ATTR1_NO_THREAT (0x400).  Charge generates no threat and does not
--   engage.  For a tank's opener that is exactly wrong -- Intervene keeps
--   normal threat so the charge actually pulls.
--
--   SPELL_ATTR0_NOT_IN_COMBAT_ONLY_PEACEFUL.  Neither spell has it any more
--   (woa_2026_08_08_05.sql stripped it from Charge), but Charge has the
--   restriction re-imposed in C++ by spell_warr_charge_in_combat unless the
--   warrior has Juggernaut.  That script is registered on -100 only, so
--   Intervene is freely usable in combat -- which is the whole point of giving
--   Protection its own version.
--
-- The -10% damage debuff survives the redesign and reads better than it did:
-- on an ally it was a threat-management tax, on an enemy it is straightforward
-- mitigation for the target you just committed to.  200640 is renamed from
-- "Interceded" to "Staggered" and re-pointed at the enemy.
--
-- Core's spell_warr_intervene (src/server/scripts/Spells/spell_warrior.cpp:128)
-- is unregistered.  It hooks EFFECT_1 / SPELL_EFFECT_APPLY_AURA to cast 59667,
-- the threat reduction on the intervened ally.  With Effect2 blanked the hook
-- can never fire, but leaving the registration in place would imply the ability
-- still has an ally half.
--
-- Rage: still free and still generates none.  Charge's +10 rage is masked to
-- Charge alone, and Improved Charge is an Arms talent.
--
-- Spells:
--   3411   = Intervene
--   200640 = Staggered (was Interceded)
--   100    = Charge, 20252 = Intercept -- the two spells this now mirrors
-- ============================================================

-- ------------------------------------------------------------
-- Retire core's ally-side script
-- ------------------------------------------------------------
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_warr_intervene';

-- ------------------------------------------------------------
-- 3411: charge an enemy
-- ------------------------------------------------------------
-- Generated by gen_sql.py on 2026-08-09
-- Overrides: EffectImplicitTargetA1: 6 -> 6, Effect2: 0 -> 0, EffectApplyAuraName2: 0 -> 0, EffectBasePoints2: 0 -> 0, EffectDieSides2: 0 -> 0, EffectImplicitTargetA2: 0 -> 0, EffectBonusMultiplier2: 0.0 -> 0, EffectImplicitTargetA3: 6 -> 6, AttributesEx5: 0 -> 0, AttributesEx6: 8388608 -> 8388608, SpellDescription0: 'Charge an enemy, generating no rage and reducing the damage they deal by $200640s1% for $200640d.  Usable in combat, and only in Defensive Stance.' -> 'Charge an enemy, generating no rage and reducing the damage they deal by $200640s1% for $200640d.  Usable in combat, and only in Defensive Stance.', SpellToolTip0: 'The next melee or ranged attack made against you will be made against the intervening warrior instead.' -> ''

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 3411;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(3411, 0, 0, 0, 536870928, 0, 0, 0, 0, 0, 8388608, 262144, 131072, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 65219, 1, 30000, 0, 0, 0, 0, 680, 100, 1, 0, 70, 70, 1, 1, 0, 0, 0, 0, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 96, 0, 64, 1, 0, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 6, 0, 6, 0, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200640, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9107, 0, 2205, 0, 0, 'Intervene', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Charge an enemy, generating no rage and reducing the damage they deal by $200640s1% for $200640d.  Usable in combat, and only in Defensive Stance.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 0, 0, 0, 0, 4, 0, 65536, 0, 0, 0, 2, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0);

-- ------------------------------------------------------------
-- 200640: now a debuff on the charged enemy.
-- UPDATE, not a re-INSERT: 200640 is a custom spell and does not exist in the
-- base Spell.dbc, so gen_sql.py cannot regenerate its row -- and a hand-built
-- full-row INSERT would quietly revert the duration and aura type that
-- woa_2026_08_09_05.sql set.
-- ------------------------------------------------------------
UPDATE `alonecraft_spell_dbc`
   SET `EffectImplicitTargetA1` = 6,
       `SpellName0`             = 'Staggered',
       `SpellDescription0`      = 'Damage done reduced by $s1%.',
       `SpellToolTip0`          = 'Damage done reduced by $s1%.'
 WHERE `ID` = 200640;
