-- ============================================================
-- Marksmanship: Improved Concussive Shot -> Lethal Instincts
-- ============================================================
--
-- TODO.md: "Your Arcane Shot, Chimera Shot, Aimed Shot and Steady Shot have a
--  50/100% chance to refresh the duration of Instinctive Fire, and Instinctive
--  Fire is extended by 3/6 seconds (2 ranks)"
--
-- Renamed from Improved Concussive Shot and given Instinctive Fire's own icon
-- (SpellIconID 5000), because the talent no longer has anything to do with
-- Concussive Shot -- it exists to sustain and lengthen Instinctive Fire.
--
-- Two halves, and only the first needs code:
--
--   Effect1 (dummy) -- the refresh.  This cannot be data.  A DBC
--   EffectTriggerSpell of 200742 would *apply* the buff, handing permanent
--   ranged haste to a hunter who never presses the button, and a CasterAuraSpell
--   gate does not save it: a proc-triggered cast runs with TRIGGERED_FULL_MASK,
--   which contains TRIGGERED_IGNORE_CASTER_AURASTATE (SpellDefines.h:145), so
--   the check at Spell.cpp:5756 never runs.  spell_hun_lethal_instincts
--   refreshes only what is already there.
--
--   Effect2 (ADD_FLAT_MODIFIER, MiscValue 1 = SPELLMOD_DURATION) -- the
--   extension.  Pure data, and it applies to EVERY application of the buff,
--   including a plain Instinctive Fire cast with no proc involved.  That is why
--   it is a spellmod rather than something the refresh handler does: the script
--   only ever sees the proc path.
--
-- Base points 2999/5999, not 3000/6000: a flat modifier's value is
-- BasePoints + max(1, DieSides), and $/1000;s2 renders that same total as 3 / 6.
--
-- The class mask goes in EffectSpellClassMaskB3 -- effect TWO, word THREE.  The
-- letter is the effect index and the digit is the flag96 word; Missile Barrage
-- (44401) settles it, carrying A1 = B1 = C1 = 2048 for three effects that each
-- modify Arcane Missiles, whose family flag is word0 0x800.
--
-- EffectSpellClassMaskA1 is zeroed deliberately.  512 (Concussive Shot) was the
-- mask for the old ADD_FLAT_MODIFIER; a stale mask left on a dummy effect is the
-- inheritance trap CLAUDE.md calls out for cloned rows.



-- ============================================================
-- Lethal Instincts rank 1 -- 50% refresh, +3s Instinctive Fire
-- ============================================================
-- Generated by gen_sql.py on 2026-08-12
-- Overrides: SpellName0: 'Improved Concussive Shot' -> 'Lethal Instincts', SpellIconID: 15 -> 5000, EffectApplyAuraName1: 4 -> 4, EffectMiscValue1: 0 -> 0, EffectBasePoints1: 0 -> 0, EffectDieSides1: 0 -> 0, EffectSpellClassMaskA1: 0 -> 0, ProcChance: 50 -> 50, Effect2: 0 -> 6, EffectApplyAuraName2: 0 -> 107, EffectMiscValue2: 0 -> 1, EffectBasePoints2: 0 -> 2999, EffectDieSides2: 0 -> 1, EffectImplicitTargetA2: 0 -> 1, EffectSpellClassMaskB3: 0 -> 4194304, SpellDescription0: 'Your Arcane Shot, Chimera Shot, Aimed Shot and Steady Shot have a $h% chance to refresh the duration of Instinctive Fire.' -> 'Your Arcane Shot, Chimera Shot, Aimed Shot and Steady Shot have a $h% chance to refresh the duration of Instinctive Fire.  Increases the duration of Instinctive Fire by $/1000;s2 sec.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 19407;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(19407, 0, 0, 0, 448, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 6, 0, 0, 1, 0, 0, 0, 0, 0, 2999, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 4, 107, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4194304, 0, 0, 0, 0, 0, 5000, 0, 0, 'Lethal Instincts', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Rank 1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Your Arcane Shot, Chimera Shot, Aimed Shot and Steady Shot have a $h% chance to refresh the duration of Instinctive Fire.  Increases the duration of Instinctive Fire by $/1000;s2 sec.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0);


-- ============================================================
-- Lethal Instincts rank 2 -- 100% refresh, +6s Instinctive Fire
-- ============================================================
-- Generated by gen_sql.py on 2026-08-12
-- Overrides: SpellName0: 'Improved Concussive Shot' -> 'Lethal Instincts', SpellIconID: 15 -> 5000, EffectApplyAuraName1: 4 -> 4, EffectMiscValue1: 0 -> 0, EffectBasePoints1: 0 -> 0, EffectDieSides1: 0 -> 0, EffectSpellClassMaskA1: 0 -> 0, ProcChance: 100 -> 100, Effect2: 0 -> 6, EffectApplyAuraName2: 0 -> 107, EffectMiscValue2: 0 -> 1, EffectBasePoints2: 0 -> 5999, EffectDieSides2: 0 -> 1, EffectImplicitTargetA2: 0 -> 1, EffectSpellClassMaskB3: 0 -> 4194304, SpellDescription0: 'Your Arcane Shot, Chimera Shot, Aimed Shot and Steady Shot have a $h% chance to refresh the duration of Instinctive Fire.' -> 'Your Arcane Shot, Chimera Shot, Aimed Shot and Steady Shot have a $h% chance to refresh the duration of Instinctive Fire.  Increases the duration of Instinctive Fire by $/1000;s2 sec.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 19412;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(19412, 0, 0, 0, 448, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 6, 0, 0, 1, 0, 0, 0, 0, 0, 5999, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 4, 107, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4194304, 0, 0, 0, 0, 0, 5000, 0, 0, 'Lethal Instincts', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Rank 2', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Your Arcane Shot, Chimera Shot, Aimed Shot and Steady Shot have a $h% chance to refresh the duration of Instinctive Fire.  Increases the duration of Instinctive Fire by $/1000;s2 sec.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0);

-- ============================================================
-- Instinctive Fire's buff needs a family flag to be modifiable
-- ============================================================
--
-- Without this the +3/6 sec above silently does NOTHING, with no error.
-- Player::IsAffectedBySpellMod requires `spellmod->mask & spellInfo->
-- SpellFamilyFlags` to be non-zero, and Aura::CalcMaxDuration applies
-- SPELLMOD_DURATION against the aura's OWN spell -- which is 200742, the buff,
-- not 1462, the shot.  200742 shipped with SpellFamilyName 9 but all three
-- family flag words zero, so no mask could ever match it.
--
-- This is the same trap 1462 hit during the Beast Mastery pass, one spell
-- along: the shot was given word2 bit21 so Invigoration could modify it, and
-- nobody noticed the BUFF had no bit at all because nothing modified it yet.
--
-- Bit 22 of word 2 (4194304), NOT bit 21.  Reusing the shot's bit would make
-- Invigoration's free-cast cost modifier (200757) match the buff as well as the
-- shot, and a charge-limited modifier that matches two spells is consumed by
-- whichever the engine reaches first.  Bit 22 was verified free by scanning
-- every family-9 record in Spell.dbc: no spell carries it as a flag, and no
-- effect anywhere masks it.
--
-- UPDATE, not a re-INSERT: 200742's full row lives in woa_2026_08_11_03.sql,
-- which sorts earlier, so this lands on top of it.

UPDATE `alonecraft_spell_dbc` SET `SpellFamilyFlags2` = 4194304 WHERE `ID` = 200742;

-- ============================================================
-- Lethal Instincts: proc configuration
-- ============================================================
--
-- Two rows rather than one negative row, because the 50/100% split lives in
-- spell_proc.Chance, which is keyed by spell id.
--
-- SpellFamilyMask0 133120 = Arcane Shot (0x800) | Aimed Shot (0x20000).
-- SpellFamilyMask1 1      = Steady Shot.
-- SpellFamilyMask2 1      = Chimera Shot.
--
-- ProcFlags 256 = PROC_FLAG_DONE_SPELL_RANGED_DMG_CLASS (SpellMgr.h:122).
--
-- SpellPhaseMask 2 (PROC_SPELL_PHASE_HIT) is load-bearing: a row with phase 0
-- silently never triggers.
--
-- AttributesMask 0 is correct here.  All four shots are real player casts, so
-- Aura::IsProcTriggeredOnEvent's triggered-spell filter (SpellAuras.cpp:2152)
-- never rejects them and PROC_ATTR_TRIGGERED_CAN_PROC is not needed.
--
-- The DBC ProcChance on 19407/19412 is set to 50/100 to match, because $h in
-- the talent description reads the DBC value, NOT spell_proc.Chance.  The two
-- are independent and nothing but reading the tooltip catches a mismatch.

DELETE FROM `spell_proc` WHERE `SpellId` IN (19407, 19412);
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(19407, 0, 9, 133120, 1, 1, 256, 0, 2, 0, 0, 0, 0, 50, 0, 0),
(19412, 0, 9, 133120, 1, 1, 256, 0, 2, 0, 0, 0, 0, 100, 0, 0);

DELETE FROM `spell_script_names` WHERE `spell_id` IN (19407, 19412);
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(19407, 'spell_hun_lethal_instincts'),
(19412, 'spell_hun_lethal_instincts');
