-- ============================================================
-- Warrior (Protection): Improved Spell Reflection -> Spellshield
-- ============================================================
-- TODO.md: "Improved Spell Reflection (Renamed to Spellshield) (0, 3):
--           Redesigned. You have a chance equal to your block chance to reduce
--           damage taken by spells by an amount equal to your block value.
--           (2 ranks)"
--
-- Rank scaling: 50% and 100% of block value.  TODO.md gives no per-rank
-- numbers, and the block-value fraction is the only dial that does not change
-- what the talent IS -- scaling the chance instead would break the "equal to
-- your block chance" identity that the whole design rests on.
--
-- What it was: reflect the next spell cast at the 2/4 closest PARTY members,
-- plus -4/-6% chance to be hit by spells.  The party half is worth nothing on a
-- solo fork -- it is a talent about protecting other people, on a 10 minute
-- cooldown ability.  What survives in spirit is the idea that a Protection
-- warrior should have an answer to magic damage at all, which stock 3.3.5
-- otherwise gives them almost none of: block, parry and dodge are all physical.
--
-- This makes the shield work against spells.  It is a genuinely new mechanic --
-- there is nothing in 3.3.5 that rolls a defensive chance against magic -- but
-- it is built out of numbers the warrior already has, so it scales with tanking
-- gear rather than needing its own budget.
--
-- DBC layout:
--
--   Effect1  SPELL_AURA_SCHOOL_ABSORB, MiscValue 126.  126 = 0x7E, every school
--            except physical (0x1) -- "damage taken by spells".  Base points are
--            0 because the script sets the pool; see below.
--   Effect2  SPELL_AURA_DUMMY, 50 / 100.  The percentage of block value, read
--            by the script.  A dummy because there is no aura type meaning
--            "a script may consult me".
--   Effect3  blanked (was SPELL_AURA_MOD_ATTACKER_SPELL_HIT_CHANCE).
--
-- Core's spell_warr_improved_spell_reflection and its _trigger partner are
-- unregistered below.  They are written against the old design -- the trigger
-- one casts 59725 at party members with SPELLVALUE_MAX_TARGETS taken from the
-- old Effect2 amount -- and would now read a percentage as a target count.
-- Deleting the spell_script_names rows is the module-only way to do this; the
-- core file is not touched.  (Same approach as Second Wind in
-- woa_2026_08_07_08.sql.)
--
-- The absorb pool is set to ~2 billion by the script with canBeRecalculated
-- false.  This is a permanent passive, not a shield with a budget: the pool
-- must never be what runs out, because every hit is already gated by the block
-- roll.  Same idiom as MagicAbsorption.cpp.
--
-- No shield equipped means no absorb and it needs no check: block chance is 0
-- without one, so the roll never succeeds.
--
-- Script: spell_warr_spellshield
-- (modules/world_of_alonecraft/src/WarriorSpellshield.cpp).
--
-- Spells:
--   59088 / 59089 = Spellshield ranks 1-2 (was Improved Spell Reflection)
--   59725         = Improved Spell Reflection (trigger) -- now orphaned, left
--                   in the DBC untouched, simply no longer cast by anything
-- ============================================================

-- ------------------------------------------------------------
-- Retire core's scripts for the old design
-- ------------------------------------------------------------
DELETE FROM `spell_script_names` WHERE `ScriptName` IN
    ('spell_warr_improved_spell_reflection', 'spell_warr_improved_spell_reflection_trigger');

-- ------------------------------------------------------------
-- The two ranks
-- ------------------------------------------------------------
-- Generated by gen_sql.py on 2026-08-09
-- Overrides: Effect1: 0 -> 6, EffectApplyAuraName1: 0 -> 69, EffectBasePoints1: -1 -> 0, EffectDieSides1: 1 -> 0, EffectMiscValue1: 0 -> 126, EffectImplicitTargetA1: 0 -> 1, Effect2: 6 -> 6, EffectApplyAuraName2: 4 -> 4, EffectBasePoints2: 1 -> 49, EffectDieSides2: 1 -> 1, EffectMiscValue2: 0 -> 0, EffectImplicitTargetA2: 1 -> 1, EffectSpellClassMaskA2: 2 -> 0, EffectSpellClassMaskB2: 0 -> 0, EffectSpellClassMaskC2: 0 -> 0, Effect3: 6 -> 0, EffectApplyAuraName3: 186 -> 0, EffectBasePoints3: -3 -> 0, EffectDieSides3: 1 -> 0, EffectMiscValue3: 126 -> 0, SpellName0: 'Improved Spell Reflection' -> 'Spellshield', SpellDescription0: 'Reduces the chance you'll be hit by spells by $s3% and when the ability is used it will reflect the first spell cast against the $s2 closest party members within 20 yards.' -> 'You have a chance equal to your block chance to absorb spell damage equal to $s2% of your block value.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 59088;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(59088, 0, 0, 0, 464, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 6, 0, 0, 1, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 69, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 126, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1935, 0, 0, 'Spellshield', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Rank 1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'You have a chance equal to your block chance to absorb spell damage equal to $s2% of your block value.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);


-- Generated by gen_sql.py on 2026-08-09
-- Overrides: Effect1: 0 -> 6, EffectApplyAuraName1: 0 -> 69, EffectBasePoints1: -1 -> 0, EffectDieSides1: 1 -> 0, EffectMiscValue1: 0 -> 126, EffectImplicitTargetA1: 0 -> 1, Effect2: 6 -> 6, EffectApplyAuraName2: 4 -> 4, EffectBasePoints2: 3 -> 99, EffectDieSides2: 1 -> 1, EffectMiscValue2: 0 -> 0, EffectImplicitTargetA2: 1 -> 1, EffectSpellClassMaskA2: 2 -> 0, EffectSpellClassMaskB2: 0 -> 0, EffectSpellClassMaskC2: 0 -> 0, Effect3: 6 -> 0, EffectApplyAuraName3: 186 -> 0, EffectBasePoints3: -5 -> 0, EffectDieSides3: 1 -> 0, EffectMiscValue3: 126 -> 0, SpellName0: 'Improved Spell Reflection' -> 'Spellshield', SpellDescription0: 'Reduces the chance you'll be hit by spells by $s3% and when the ability is used it will reflect the first spell cast against the $s2 closest party members within 20 yards.' -> 'You have a chance equal to your block chance to absorb spell damage equal to $s2% of your block value.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 59089;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(59089, 0, 0, 0, 464, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 6, 0, 0, 1, 0, 0, 0, 0, 0, 99, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 69, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 126, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1935, 0, 0, 'Spellshield', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Rank 2', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'You have a chance equal to your block chance to absorb spell damage equal to $s2% of your block value.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);


-- ------------------------------------------------------------
-- Drop the old proc row; Spellshield is an absorb, not a proc
-- ------------------------------------------------------------
DELETE FROM `spell_proc` WHERE `SpellId` = -59088;

-- ------------------------------------------------------------
-- Script registration -- see modules/world_of_alonecraft/src/WarriorSpellshield.cpp
-- ------------------------------------------------------------
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_warr_spellshield';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(59088, 'spell_warr_spellshield'),
(59089, 'spell_warr_spellshield');
