-- ============================================================
-- Warrior (Protection): Improved Bloodrage -> Controlled Aggression
-- ============================================================
-- "Improved Bloodrage (Renamed to Controlled Aggression) (3, 2): Redesigned.
--  While Bloodrage or Berserker Rage is active, 50/100% of your shield block
--  value is added to your attack power. (2 ranks)"
--
-- What it was: the Shield Slam stack ramp from woa_2026_08_09_13.sql (payload
-- buffs 200647/200648, fixed in woa_2026_08_09_28.sql), retired below.
--
-- Why this shape.  Protection's block value is already the tree's central
-- number -- Toughness scales it off Strength, Shield Mastery multiplies it,
-- Spellshield turns it into magic absorb and Barricade into healing -- but none
-- of that touched the damage a tank does.  This makes a defensive stat pay out
-- as offence for the duration of a rage cooldown, so pressing Bloodrage is a
-- damage decision as well as a resource one, and the two rage cooldowns stop
-- being pure filler on a full rage bar.
--
-- Both gates are real 10 second windows the player can see on their buff bar:
--   29131 = Bloodrage's periodic-energize aura.  NOT 2687, which is
--           instantaneous (ENERGIZE + TRIGGER_SPELL); 29131 is the one a
--           warrior actually "has active".  Same reasoning as the talent's
--           previous design.
--   18499 = Berserker Rage, which Alonecraft already rebuilt in
--           woa_2026_08_08_03.sql to grant +100% rage from damage dealt.
--
-- Handled by DBC:
--   Everything except the amount.
--
--   EffectApplyAuraName1 = 99 SPELL_AURA_MOD_ATTACK_POWER
--   EffectBasePoints1    = 49 / 99, so $s1 renders 50 / 100 and the amount the
--                          script receives is 50 / 100.
--
--   The proc plumbing is cleared: EffectTriggerSpell1 200647/200648 -> 0 and
--   Attributes 262352 -> 464, the standard passive-talent shape.
--
-- Handled by C++ (modules/world_of_alonecraft/src/WarriorProtConversions.cpp,
-- spell_warr_controlled_aggression):
--   The amount, and the two-buff gate.
--
-- Why a script at all.  Nothing converts block value into a stat.  Block value
-- is not a stat or a rating -- Player::GetShieldBlockValue (Player.cpp:5115)
-- computes it from Strength and the SHIELD_BLOCK_VALUE base mods -- so
-- SPELL_AURA_MOD_RATING_FROM_STAT (220), the only conversion aura in 3.3.5,
-- cannot see it from either end.  The value is therefore computed and refreshed
-- on the same 2 second heartbeat the sibling conversions use, which is also
-- what makes gaining and losing the gating buff take effect.
--
-- SPELL_AURA_MOD_ATTACK_POWER honours AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK
-- (SpellAuraEffects.cpp:4890), so RecalculateAmount() genuinely re-applies
-- through HandleStatFlatModifier rather than only updating a stored number.
--
-- No circularity: GetShieldBlockValue reads Strength and the block-value aura
-- mods; flat attack power feeds neither.
--
-- Spells:
--   12301 / 12818 = Controlled Aggression ranks 1-2
--   200647 / 200648 = the retired Shield Slam stack buffs
-- ============================================================


-- ============================================================
-- Controlled Aggression rank 1: 50% of block value as attack power
-- ============================================================
-- Generated by gen_sql.py on 2026-08-09
-- Overrides: Attributes: 262352 -> 464, ProcFlags: 0 -> 0, ProcChance: 101 -> 101, Effect1: 6 -> 6, EffectApplyAuraName1: 42 -> 99, EffectBasePoints1: -1 -> 49, EffectDieSides1: 1 -> 1, EffectMiscValue1: 0 -> 0, EffectTriggerSpell1: 200647 -> 0, EffectImplicitTargetA1: 1 -> 1, EffectSpellClassMaskA1: 0 -> 0, EffectSpellClassMaskB1: 0 -> 0, EffectSpellClassMaskC1: 0 -> 0, EffectSpellClassMaskA2: 0 -> 0, EffectSpellClassMaskB2: 0 -> 0, EffectSpellClassMaskC2: 0 -> 0, SpellName0: 'Improved Bloodrage' -> 'Controlled Aggression', SpellDescription0: 'Each time you take damage while Bloodrage is active, the damage of your Shield Slam is increased by $200647s1%.  Stacks up to 5 times.' -> 'While Bloodrage or Berserker Rage is active, $s1% of your shield block value is added to your attack power.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 12301;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(12301, 0, 0, 0, 464, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 101, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 0, 0, 1, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 86, 0, 50, 'Controlled Aggression', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Rank 1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'While Bloodrage or Berserker Rage is active, $s1% of your shield block value is added to your attack power.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0);


-- ============================================================
-- Controlled Aggression rank 2: 100% of block value as attack power
-- ============================================================
-- Generated by gen_sql.py on 2026-08-09
-- Overrides: Attributes: 262352 -> 464, ProcFlags: 0 -> 0, ProcChance: 101 -> 101, Effect1: 6 -> 6, EffectApplyAuraName1: 42 -> 99, EffectBasePoints1: -1 -> 99, EffectDieSides1: 1 -> 1, EffectMiscValue1: 0 -> 0, EffectTriggerSpell1: 200648 -> 0, EffectImplicitTargetA1: 1 -> 1, EffectSpellClassMaskA1: 0 -> 0, EffectSpellClassMaskB1: 0 -> 0, EffectSpellClassMaskC1: 0 -> 0, EffectSpellClassMaskA2: 0 -> 0, EffectSpellClassMaskB2: 0 -> 0, EffectSpellClassMaskC2: 0 -> 0, SpellName0: 'Improved Bloodrage' -> 'Controlled Aggression', SpellDescription0: 'Each time you take damage while Bloodrage is active, the damage of your Shield Slam is increased by $200648s1%.  Stacks up to 5 times.' -> 'While Bloodrage or Berserker Rage is active, $s1% of your shield block value is added to your attack power.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 12818;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(12818, 0, 0, 0, 464, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 101, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 0, 0, 1, 0, 0, 0, 0, 0, 99, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 86, 0, 50, 'Controlled Aggression', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Rank 2', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'While Bloodrage or Berserker Rage is active, $s1% of your shield block value is added to your attack power.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0);

-- ------------------------------------------------------------
-- Retire the proc from woa_2026_08_09_13.sql
-- ------------------------------------------------------------
-- The talent is a plain passive now, so there is nothing to proc.  Leaving the
-- row would keep spell_proc pointing at an aura with no
-- SPELL_AURA_PROC_TRIGGER_SPELL effect.
DELETE FROM `spell_proc` WHERE `SpellId` = -12301;

-- The payload buffs have no caster left.  Deleting the rows drops them from the
-- built Spell.dbc entirely, since 200647/200648 exist only as Alonecraft
-- overrides and have no base row to fall back to.
DELETE FROM `alonecraft_spell_dbc` WHERE `ID` IN (200647, 200648);

-- ------------------------------------------------------------
-- Script registration -- modules/world_of_alonecraft/src/WarriorProtConversions.cpp
-- ------------------------------------------------------------
-- Renamed from spell_warr_imp_bloodrage, whose registration lived in
-- woa_2026_08_09_13.sql and named 12301 only.  Both DELETEs are needed: the old
-- name's row, and this name's rows if the file is re-applied.
DELETE FROM `spell_script_names` WHERE `ScriptName` IN ('spell_warr_imp_bloodrage', 'spell_warr_controlled_aggression');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(12301, 'spell_warr_controlled_aggression'),
(12818, 'spell_warr_controlled_aggression');
