-- ==========================================================================
-- Item Upgrade Tools -- auto-generated by tools/gen_upgrade_tools.py
-- ==========================================================================
--
-- 16 consumables sold by Artificer Volen (200011), one per
-- target level.  Using one gives the item-targeting cursor; clicking an
-- item upgrades it to that tool's level.
--
-- Target levels are absolute multiples of 5.  That only holds because
-- gen_item_variants.py snaps them there -- with relative steps a level-23
-- item's chain runs 28/33/38 and a per-level tool would never match it.
--
-- Every tool needs an item_dbc row as well as item_template: without one
-- the template is silently discarded at load (ObjectMgr.cpp:3487).

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` BETWEEN 201000 AND 201015;
DELETE FROM `spell_script_names`  WHERE `spell_id` BETWEEN 201000 AND 201015;
DELETE FROM `npc_vendor`          WHERE `entry` = 200011;
DELETE FROM `item_template`       WHERE `entry` BETWEEN 200100 AND 200115;
DELETE FROM `item_dbc`            WHERE `ID`    BETWEEN 200100 AND 200115;

-- -- spells -----------------------------------------------------------
-- Flickering Ethereal Mote (level 5)
INSERT INTO `alonecraft_spell_dbc` VALUES (201000, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 5, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Flickering Ethereal Mote', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 5, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 5, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Dim Ethereal Mote (level 10)
INSERT INTO `alonecraft_spell_dbc` VALUES (201001, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 10, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Dim Ethereal Mote', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 10, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 10, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Glimmering Ethereal Mote (level 15)
INSERT INTO `alonecraft_spell_dbc` VALUES (201002, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 15, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Glimmering Ethereal Mote', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 15, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 15, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Radiant Ethereal Mote (level 20)
INSERT INTO `alonecraft_spell_dbc` VALUES (201003, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 20, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Radiant Ethereal Mote', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 20, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 20, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Fractured Ethereal Shard (level 25)
INSERT INTO `alonecraft_spell_dbc` VALUES (201004, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 25, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Fractured Ethereal Shard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 25, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 25, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Lucid Ethereal Shard (level 30)
INSERT INTO `alonecraft_spell_dbc` VALUES (201005, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 30, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Lucid Ethereal Shard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 30, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 30, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Gleaming Ethereal Shard (level 35)
INSERT INTO `alonecraft_spell_dbc` VALUES (201006, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 35, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Gleaming Ethereal Shard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 35, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 35, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Brilliant Ethereal Shard (level 40)
INSERT INTO `alonecraft_spell_dbc` VALUES (201007, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 40, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Brilliant Ethereal Shard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 40, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 40, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Shifting Nexus Prism (level 45)
INSERT INTO `alonecraft_spell_dbc` VALUES (201008, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 45, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Shifting Nexus Prism', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 45, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 45, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Resonant Nexus Prism (level 50)
INSERT INTO `alonecraft_spell_dbc` VALUES (201009, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 50, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Resonant Nexus Prism', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 50, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 50, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Coalesced Nexus Prism (level 55)
INSERT INTO `alonecraft_spell_dbc` VALUES (201010, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 55, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Coalesced Nexus Prism', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 55, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 55, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Refracted Nexus Prism (level 60)
INSERT INTO `alonecraft_spell_dbc` VALUES (201011, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 60, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Refracted Nexus Prism', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 60, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 60, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Woven Astral Sigil (level 65)
INSERT INTO `alonecraft_spell_dbc` VALUES (201012, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 65, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Woven Astral Sigil', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 65, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 65, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Ascendant Astral Sigil (level 70)
INSERT INTO `alonecraft_spell_dbc` VALUES (201013, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 70, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Ascendant Astral Sigil', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 70, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 70, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Transcendent Astral Sigil (level 75)
INSERT INTO `alonecraft_spell_dbc` VALUES (201014, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 75, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Transcendent Astral Sigil', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 75, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 75, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
-- Eternal Astral Sigil (level 80)
INSERT INTO `alonecraft_spell_dbc` VALUES (201015, 0, 0, 0, 262144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 15, 0, 0, 0, 101, 0, 80, 45, 45, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 77, 0, 0, 1, 0, 0, 0, 0, 0, 1799, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3324, 0, 2192, 0, 0, 'Eternal Astral Sigil', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Reforges an item to level 80, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Reforges an item to level 80, scaling its statistics to match. The item must be one you could otherwise upgrade.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);

-- -- script binding ---------------------------------------------------
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(201000, 'spell_item_upgrade_tool'),
(201001, 'spell_item_upgrade_tool'),
(201002, 'spell_item_upgrade_tool'),
(201003, 'spell_item_upgrade_tool'),
(201004, 'spell_item_upgrade_tool'),
(201005, 'spell_item_upgrade_tool'),
(201006, 'spell_item_upgrade_tool'),
(201007, 'spell_item_upgrade_tool'),
(201008, 'spell_item_upgrade_tool'),
(201009, 'spell_item_upgrade_tool'),
(201010, 'spell_item_upgrade_tool'),
(201011, 'spell_item_upgrade_tool'),
(201012, 'spell_item_upgrade_tool'),
(201013, 'spell_item_upgrade_tool'),
(201014, 'spell_item_upgrade_tool'),
(201015, 'spell_item_upgrade_tool');

-- -- items ------------------------------------------------------------
-- class 15 / subclass 0 = Miscellaneous/Junk, so they stack and vendor
-- cleanly.  spelltrigger 0 = on use; spellcharges -1 = consumed on use.
INSERT INTO `item_template`
  (`entry`, `class`, `subclass`, `name`, `displayid`, `Quality`, `Flags`,
   `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `stackable`,
   `Material`, `sheath`, `spellid_1`, `spelltrigger_1`, `spellcharges_1`,
   `bonding`, `Description`, `RequiredLevel`, `ItemLevel`)
VALUES
(200100, 15, 0, 'Flickering Ethereal Mote', 6533, 3, 0, 1, 1400, 280, 0, 20, 0, 0, 201000, 0, -1, 0, 'Reforges an item to level 5.', 1, 5),
(200101, 15, 0, 'Dim Ethereal Mote', 6533, 3, 0, 1, 8400, 1680, 0, 20, 0, 0, 201001, 0, -1, 0, 'Reforges an item to level 10.', 1, 10),
(200102, 15, 0, 'Glimmering Ethereal Mote', 6533, 3, 0, 1, 24000, 4800, 0, 20, 0, 0, 201002, 0, -1, 0, 'Reforges an item to level 15.', 1, 15),
(200103, 15, 0, 'Radiant Ethereal Mote', 6533, 3, 0, 1, 50700, 10140, 0, 20, 0, 0, 201003, 0, -1, 0, 'Reforges an item to level 20.', 1, 20),
(200104, 15, 0, 'Fractured Ethereal Shard', 6533, 3, 0, 1, 90500, 18100, 0, 20, 0, 0, 201004, 0, -1, 0, 'Reforges an item to level 25.', 1, 25),
(200105, 15, 0, 'Lucid Ethereal Shard', 6533, 3, 0, 1, 145500, 29100, 0, 20, 0, 0, 201005, 0, -1, 0, 'Reforges an item to level 30.', 1, 30),
(200106, 15, 0, 'Gleaming Ethereal Shard', 6533, 3, 0, 1, 217200, 43440, 0, 20, 0, 0, 201006, 0, -1, 0, 'Reforges an item to level 35.', 1, 35),
(200107, 15, 0, 'Brilliant Ethereal Shard', 6533, 3, 0, 1, 307300, 61460, 0, 20, 0, 0, 201007, 0, -1, 0, 'Reforges an item to level 40.', 1, 40),
(200108, 15, 0, 'Shifting Nexus Prism', 6533, 3, 0, 1, 417400, 83480, 0, 20, 0, 0, 201008, 0, -1, 0, 'Reforges an item to level 45.', 1, 45),
(200109, 15, 0, 'Resonant Nexus Prism', 6533, 3, 0, 1, 549000, 109800, 0, 20, 0, 0, 201009, 0, -1, 0, 'Reforges an item to level 50.', 1, 50),
(200110, 15, 0, 'Coalesced Nexus Prism', 6533, 3, 0, 1, 703300, 140660, 0, 20, 0, 0, 201010, 0, -1, 0, 'Reforges an item to level 55.', 1, 55),
(200111, 15, 0, 'Refracted Nexus Prism', 6533, 3, 0, 1, 881900, 176380, 0, 20, 0, 0, 201011, 0, -1, 0, 'Reforges an item to level 60.', 1, 60),
(200112, 15, 0, 'Woven Astral Sigil', 6533, 3, 0, 1, 1085900, 217180, 0, 20, 0, 0, 201012, 0, -1, 0, 'Reforges an item to level 65.', 1, 65),
(200113, 15, 0, 'Ascendant Astral Sigil', 6533, 3, 0, 1, 1316700, 263340, 0, 20, 0, 0, 201013, 0, -1, 0, 'Reforges an item to level 70.', 1, 70),
(200114, 15, 0, 'Transcendent Astral Sigil', 6533, 3, 0, 1, 1575400, 315080, 0, 20, 0, 0, 201014, 0, -1, 0, 'Reforges an item to level 75.', 1, 75),
(200115, 15, 0, 'Eternal Astral Sigil', 6533, 3, 0, 1, 1863200, 372640, 0, 20, 0, 0, 201015, 0, -1, 0, 'Reforges an item to level 80.', 1, 80);

-- -- item_dbc (mandatory; also feeds the client's patched Item.dbc) ----
INSERT INTO `item_dbc`
  (`ID`, `ClassID`, `SubclassID`, `Sound_Override_Subclassid`, `Material`,
   `DisplayInfoID`, `InventoryType`, `SheatheType`) VALUES
(200100, 15, 0, -1, 0, 6533, 0, 0),
(200101, 15, 0, -1, 0, 6533, 0, 0),
(200102, 15, 0, -1, 0, 6533, 0, 0),
(200103, 15, 0, -1, 0, 6533, 0, 0),
(200104, 15, 0, -1, 0, 6533, 0, 0),
(200105, 15, 0, -1, 0, 6533, 0, 0),
(200106, 15, 0, -1, 0, 6533, 0, 0),
(200107, 15, 0, -1, 0, 6533, 0, 0),
(200108, 15, 0, -1, 0, 6533, 0, 0),
(200109, 15, 0, -1, 0, 6533, 0, 0),
(200110, 15, 0, -1, 0, 6533, 0, 0),
(200111, 15, 0, -1, 0, 6533, 0, 0),
(200112, 15, 0, -1, 0, 6533, 0, 0),
(200113, 15, 0, -1, 0, 6533, 0, 0),
(200114, 15, 0, -1, 0, 6533, 0, 0),
(200115, 15, 0, -1, 0, 6533, 0, 0);

-- -- vendor stock -----------------------------------------------------
-- maxcount 0 = unlimited stock, no restock timer.
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`) VALUES
(200011, 1, 200100, 0, 0, 0),
(200011, 2, 200101, 0, 0, 0),
(200011, 3, 200102, 0, 0, 0),
(200011, 4, 200103, 0, 0, 0),
(200011, 5, 200104, 0, 0, 0),
(200011, 6, 200105, 0, 0, 0),
(200011, 7, 200106, 0, 0, 0),
(200011, 8, 200107, 0, 0, 0),
(200011, 9, 200108, 0, 0, 0),
(200011, 10, 200109, 0, 0, 0),
(200011, 11, 200110, 0, 0, 0),
(200011, 12, 200111, 0, 0, 0),
(200011, 13, 200112, 0, 0, 0),
(200011, 14, 200113, 0, 0, 0),
(200011, 15, 200114, 0, 0, 0),
(200011, 16, 200115, 0, 0, 0);

-- -- make Volen an actual vendor --------------------------------------
-- npcflag 128 = UNIT_NPC_FLAG_VENDOR (was 1 = GOSSIP).
UPDATE `creature_template` SET `npcflag` = 128, `ScriptName` = '' WHERE `entry` = 200011;
