-- ===========================================================================
-- Warlock (Affliction): Improved Howl of Terror -> Fel Interdiction
-- ===========================================================================
--
-- TODO.md: "Improved Howl of Terror should be replaced by Fel Interdiction,
--           staggering 50% of damage taken when Fel Armor is being used.
--           Similar to the Ember Scar mechanic for Fire Mages we added, but
--           instead of clearing stacks with spell crits stacks are cleared
--           through casting drain soul, and stacks 10 times instead of 5.
--           It should also be moved to the slot to the right of Malediction."
--
-- Rename-in-place, per the house pattern (woa_2026_08_01_07.sql): talent 1668
-- keeps its ID and its rank-1 spell 30054; only the DBC row is rewritten.
-- Rank 2 (30057) is dropped -- the ability has no per-rank scaling, so this
-- becomes a 1-point talent like Sacrifice the Weak and Infernal Bargain.
--
-- The mechanic mirrors Ember Scars (MoltenArmor.cpp): a UnitScript::OnDamage
-- hook splits incoming damage and pushes the deferred half into a stacking
-- self-DoT, here Mark of Gul'dan (200520).  What differs is the clearing
-- path.  Ember Scars needs a three-hop 200041 -> 200040 -> AuraScript relay
-- because AzerothCore has no "on spell crit" hook; Drain Soul damage IS
-- reachable by an ordinary spell_proc, so Fel Interdiction's own aura is the
-- proc carrier and no relay spells exist.
--
-- Spells:
--   30054  = Fel Interdiction (talent aura; carries the stagger % AND the
--            Drain Soul proc)
--   200520 = Mark of Gul'dan (the deferred-damage DoT, 10 stacks / 10s)
-- Talent: 1668, Affliction (TabID 302), moved Tier 7 Col 0 -> Tier 7 Col 3.
-- ===========================================================================


-- ============================================================
-- Improved Howl of Terror -> Fel Interdiction (talent 1668, rank 1)
-- ============================================================
-- Effect 1 becomes SPELL_AURA_DUMMY: a marker aura the UnitScript checks for,
-- and whose amount IS the stagger percentage, so 50% lives in exactly one
-- place.  EffectDieSides1 stays 1, so CalcValue = BasePoints + 1 = 50 --
-- the value GetAmount() returns and the value $s1 renders.
--
-- The talent also carries the Drain Soul proc itself (spell_proc below), so
-- ProcFlags/ProcChance are set here to match the Syncretism precedent
-- (2026_03_30_02.sql) of declaring them in the DBC as well as the proc row.
--
-- EffectMiscValue1 10 (SPELLMOD_CASTING_TIME) and EffectSpellClassMaskA2 8
-- are Improved Howl of Terror leftovers and MUST be zeroed -- left in place
-- they would silently constrain the redesigned effect.
--
-- Both SpellDescription0 and SpellToolTip0 are set: the talent pane renders
-- the description, the buff bar renders the tooltip.
-- Generated by gen_sql.py on 2026-08-06
-- Overrides: SpellName0: 'Improved Howl of Terror' -> 'Fel Interdiction', SpellRank0: 'Rank 1' -> '', ProcFlags: 0 -> 327680, ProcChance: 101 -> 100, DurationIndex: 21 -> 21, Effect1: 6 -> 6, EffectApplyAuraName1: 107 -> 4, EffectBasePoints1: -801 -> 49, EffectDieSides1: 1 -> 1, EffectMiscValue1: 10 -> 0, EffectImplicitTargetA1: 1 -> 1, EffectSpellClassMaskA2: 8 -> 0, SpellIconID: 134 -> 2297, SpellDescription0: 'Reduces the casting time of your Howl of Terror spell by $/1000;S1 sec.' -> 'When using Fel Armor, $s1% of damage taken is converted to a Mark of Gul'dan, dealing damage periodically. Stacks can be removed by dealing damage with Drain Soul.', SpellToolTip0: '' -> 'When using Fel Armor, $s1% of damage taken is converted to a Mark of Gul'dan.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 30054;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(30054, 0, 0, 0, 464, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 327680, 100, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 0, 0, 1, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2297, 0, 0, 'Fel Interdiction', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'When using Fel Armor, $s1% of damage taken is converted to a Mark of Gul''dan, dealing damage periodically. Stacks can be removed by dealing damage with Drain Soul.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'When using Fel Armor, $s1% of damage taken is converted to a Mark of Gul''dan.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0);


-- ============================================================
-- NEW spell 200520: Mark of Gul'dan (the deferred-damage DoT)
-- ============================================================
-- Cloned from Ember Scars (200023) so the DoT plumbing matches exactly:
-- SPELL_AURA_PERIODIC_DAMAGE on a 1000ms amplitude, DurationIndex 1 (10s).
-- Changes from the base: StackAmount 5 -> 10, school Fire -> Shadow, its own
-- icon, and no ProcFlags (Ember Scars' 65536 was never used).
--
-- AttributesEx3 67108864 = SPELL_ATTR3_SUPPRESS_CASTER_PROCS.  This is load-
-- bearing: without it the DoT's own Shadow ticks could proc the redesigned
-- Siphon Life (woa_2026_08_06_00.sql) and heal back the damage the talent
-- just deferred, cancelling the mechanic.  Same precedent as
-- SpellInfoCorrections.cpp:4805, which sets it on Siphon Life's heal.
--
-- EffectBasePoints1 -1 with DieSides 1 = 0 damage.  The real per-tick amount
-- is written by C++ at apply time via AuraEffect::ChangeAmount, which is why
-- the tooltip is prose rather than a $ variable -- a variable would render 0.
-- Generated by gen_sql.py on 2026-08-06
-- Overrides: SpellName0: 'Ember Scars' -> 'Mark of Gul'dan', SpellRank0: '' -> '', AttributesEx3: 0 -> 67108864, StackAmount: 5 -> 10, DurationIndex: 1 -> 1, ProcFlags: 65536 -> 0, ProcChance: 100 -> 0, Effect1: 6 -> 6, EffectApplyAuraName1: 3 -> 3, EffectAmplitude1: 1000 -> 1000, EffectBasePoints1: -1 -> -1, EffectDieSides1: 1 -> 1, EffectImplicitTargetA1: 6 -> 1, SchoolMask: 4 -> 32, SpellIconID: 1986 -> 3172, ActiveIconID: 1986 -> 3172, SpellVisual1: 46 -> 0, SpellFamilyName: 0 -> 0, SpellDescription0: '50% of damage taken while protected by Molten Armor is dealt over time. Each hit taken adds a stack, with each stack having an equal amount of damage. Spell critical hits clear a stack of Ember Scars. ' -> 'Damage deferred by Fel Interdiction, dealt over time. Each hit taken adds a stack. Dealing damage with Drain Soul clears a stack.', SpellToolTip0: 'Damage is being delayed by your Molten Armor.' -> 'Damage is being delayed by your Fel Armor.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 200520;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(200520, 0, 0, 0, 67108864, 136, 0, 67108864, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 0, 0, 1, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3172, 3172, 0, 'Mark of Gul''dan', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Damage deferred by Fel Interdiction, dealt over time. Each hit taken adds a stack. Dealing damage with Drain Soul clears a stack.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Damage is being delayed by your Fel Armor.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0);

-- ============================================================
-- Drop the now-unused rank 2 override
-- ============================================================
-- 30057 was Improved Howl of Terror rank 2.  Fel Interdiction is a 1-point
-- talent, so the id is no longer listed by talent 1668 and reverts to its
-- untouched Blizzard row.  A character who had spent a point on rank 2 keeps
-- the orphaned spell until its next talent reset.

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 30057;


-- ============================================================
-- spell_proc: Drain Soul clears a stack of Mark of Gul'dan
-- ============================================================
-- SpellFamilyName 5 (Warlock), SpellFamilyMask0 16384 (0x4000 = Drain Soul).
-- ProcFlags 327680 = 0x50000 = DONE_SPELL_MAGIC_DMG_CLASS_NEG | DONE_PERIODIC.
-- DONE_PERIODIC is the half that matters: Drain Soul's damage is
-- SPELL_AURA_PERIODIC_DAMAGE channel ticks, so one stack clears per tick
-- (about 5 over a full channel).
--
-- AttributesMask stays 0 deliberately.  PROC_ATTR_TRIGGERED_CAN_PROC (0x2) is
-- only needed when the triggering damage comes from a spell cast as
-- triggered; periodic-damage ticks carry no Spell object and skip
-- Aura::IsProcTriggeredOnEvent's check entirely.
--
-- SpellTypeMask 1 = PROC_SPELL_TYPE_DAMAGE, SpellPhaseMask 2 = PHASE_HIT.
-- SpellPhaseMask MUST be non-zero or the proc silently never fires.

DELETE FROM `spell_proc` WHERE `SpellId` = 30054;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(30054, 0, 5, 16384, 0, 0, 327680, 1, 2, 0, 0, 0, 0, 100, 0, 0);


-- ============================================================
-- Script registration
-- ============================================================

DELETE FROM `spell_script_names` WHERE `ScriptName` IN ('spell_warl_fel_interdiction', 'spell_warl_mark_of_guldan');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(30054,  'spell_warl_fel_interdiction'),
(200520, 'spell_warl_mark_of_guldan');


-- ============================================================
-- talent_dbc: move to the slot right of Malediction, single rank
-- ============================================================
-- Malediction (talent 1667) is Tier 7 Col 2, so "the slot to the right" is
-- Tier 7 Col 3, which is empty in the stock Affliction tree.  Tier 7 Col 0 is
-- left empty by the move; the tree already has many empty slots.
--
-- Flags stays 0: Fel Interdiction is passive and must not be added to the
-- spellbook.  No prereqs.
--
-- talent_dbc overrides replace the whole record (build_dbc.py rebuilds each
-- row from TALENT_COLUMNS), so every column is restated.  Record ordering is
-- not a concern here -- build_dbc.py re-sorts by (TabID, TierID, ColumnIndex),
-- which the client requires.

DELETE FROM `talent_dbc` WHERE `ID` = 1668;
INSERT INTO `talent_dbc` (
    `ID`, `TabID`, `TierID`, `ColumnIndex`,
    `SpellRank_1`, `SpellRank_2`, `SpellRank_3`, `SpellRank_4`, `SpellRank_5`,
    `SpellRank_6`, `SpellRank_7`, `SpellRank_8`, `SpellRank_9`,
    `PrereqTalent_1`, `PrereqTalent_2`, `PrereqTalent_3`,
    `PrereqRank_1`, `PrereqRank_2`, `PrereqRank_3`,
    `Flags`, `RequiredSpellID`, `CategoryMask_1`, `CategoryMask_2`
) VALUES (
    1668, 302, 7, 3,
    30054, 0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0,
    0, 0, 0,
    0, 0, 0, 0
);
