-- ===========================================================================
-- Warlock (Affliction): NEW talent -- Malfeasance
-- ===========================================================================
--
-- TODO.md: "Below that, in the next tier and with a requirement to have
--           'Fel Interdiction', should be a new talent called 'Malfeasance':
--           'Damage from Drain Life, Shadow Bolt and Haunt has a 10/20%
--           chance to clear a stack of Mark of Gul'dan'."
--
-- Fel Interdiction (woa_2026_08_06_01.sql) can only be cleared by channelling
-- Drain Soul, which costs the whole global rotation.  Malfeasance lets the
-- normal Affliction rotation chip at the stack instead, so the talent pair
-- reads as "defer damage, then earn it back by keeping up your damage".
--
-- Spells:
--   200521 = Malfeasance Rank 1 (10%)
--   200522 = Malfeasance Rank 2 (20%)
-- Talent: NEW ID 3004 (3000 and 3003 are taken), Affliction (TabID 302),
--         Tier 8 Col 3 -- directly below Fel Interdiction at Tier 7 Col 3 --
--         gated on talent 1668 rank 1.
-- ===========================================================================


-- ============================================================
-- NEW spell 200521: Malfeasance Rank 1
-- ============================================================
-- Cloned from Improved Howl of Terror rank 2 (30057) purely for a clean
-- passive Warlock talent skeleton (Attributes 464 = passive).  The inherited
-- ADD_FLAT_MODIFIER effect, its MiscValue 10 (SPELLMOD_CASTING_TIME) and its
-- class masks are all zeroed -- left in place they would silently constrain
-- the proc.
--
-- Effect 1 is a bare SPELL_AURA_DUMMY: it exists only so the AuraScript has
-- an effect to bind OnEffectProc to.  EffectDieSides1 stays 1, so
-- CalcValue = BasePoints + 1 and $s1 renders 10 (rank 2: 20).  The C++ never
-- reads that amount -- the roll is the spell_proc Chance column below -- but
-- the two are kept equal so the tooltip cannot drift from behaviour.
-- Generated by gen_sql.py on 2026-08-06
-- Overrides: SpellName0: 'Improved Howl of Terror' -> 'Malfeasance', SpellRank0: 'Rank 2' -> 'Rank 1', DurationIndex: 21 -> 21, ProcFlags: 0 -> 327680, ProcChance: 101 -> 100, Effect1: 6 -> 6, EffectApplyAuraName1: 107 -> 4, EffectBasePoints1: -1501 -> 9, EffectDieSides1: 1 -> 1, EffectMiscValue1: 10 -> 0, EffectImplicitTargetA1: 1 -> 1, EffectSpellClassMaskA1: 0 -> 0, EffectSpellClassMaskA2: 8 -> 0, EffectSpellClassMaskA3: 0 -> 0, SpellIconID: 134 -> 113, SchoolMask: 1 -> 32, SpellDescription0: 'Reduces the casting time of your Howl of Terror spell by $/1000;S1 sec.' -> 'Damage from your Drain Life, Shadow Bolt and Haunt has a $s1% chance to clear a stack of Mark of Gul'dan.', SpellToolTip0: '' -> 'Damage from your Drain Life, Shadow Bolt and Haunt has a $s1% chance to clear a stack of Mark of Gul'dan.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 200521;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(200521, 0, 0, 0, 464, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 327680, 100, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 0, 0, 1, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 113, 0, 0, 'Malfeasance', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Rank 1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Damage from your Drain Life, Shadow Bolt and Haunt has a $s1% chance to clear a stack of Mark of Gul''dan.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Damage from your Drain Life, Shadow Bolt and Haunt has a $s1% chance to clear a stack of Mark of Gul''dan.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 1, 1, 1, 0, 0);


-- ============================================================
-- NEW spell 200522: Malfeasance Rank 2
-- ============================================================
-- Generated by gen_sql.py on 2026-08-06
-- Overrides: SpellName0: 'Improved Howl of Terror' -> 'Malfeasance', SpellRank0: 'Rank 2' -> 'Rank 2', DurationIndex: 21 -> 21, ProcFlags: 0 -> 327680, ProcChance: 101 -> 100, Effect1: 6 -> 6, EffectApplyAuraName1: 107 -> 4, EffectBasePoints1: -1501 -> 19, EffectDieSides1: 1 -> 1, EffectMiscValue1: 10 -> 0, EffectImplicitTargetA1: 1 -> 1, EffectSpellClassMaskA1: 0 -> 0, EffectSpellClassMaskA2: 8 -> 0, EffectSpellClassMaskA3: 0 -> 0, SpellIconID: 134 -> 113, SchoolMask: 1 -> 32, SpellDescription0: 'Reduces the casting time of your Howl of Terror spell by $/1000;S1 sec.' -> 'Damage from your Drain Life, Shadow Bolt and Haunt has a $s1% chance to clear a stack of Mark of Gul'dan.', SpellToolTip0: '' -> 'Damage from your Drain Life, Shadow Bolt and Haunt has a $s1% chance to clear a stack of Mark of Gul'dan.'

DELETE FROM `alonecraft_spell_dbc` WHERE `ID` = 200522;
INSERT INTO `alonecraft_spell_dbc` (`ID`, `Category`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `Stances`, `Unknown1`, `StancesNot`, `Unknown2`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `FacingCasterFlags`, `CasterAuraState`, `TargetAuraState`, `CasterAuraStateNot`, `TargetAuraStateNot`, `CasterAuraSpell`, `TargetAuraSpell`, `ExcludeCasterAuraSpell`, `ExcludeTargetAuraSpell`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaximumLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerLevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `SpellVisual1`, `SpellVisual2`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName0`, `SpellName1`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `SpellNameFlag0`, `SpellNameFlag1`, `SpellNameFlag2`, `SpellNameFlag3`, `SpellNameFlag4`, `SpellNameFlag5`, `SpellNameFlag6`, `SpellNameFlag7`, `SpellRank0`, `SpellRank1`, `SpellRank2`, `SpellRank3`, `SpellRank4`, `SpellRank5`, `SpellRank6`, `SpellRank7`, `SpellRank8`, `SpellRankFlags0`, `SpellRankFlags1`, `SpellRankFlags2`, `SpellRankFlags3`, `SpellRankFlags4`, `SpellRankFlags5`, `SpellRankFlags6`, `SpellRankFlags7`, `SpellDescription0`, `SpellDescription1`, `SpellDescription2`, `SpellDescription3`, `SpellDescription4`, `SpellDescription5`, `SpellDescription6`, `SpellDescription7`, `SpellDescription8`, `SpellDescriptionFlags0`, `SpellDescriptionFlags1`, `SpellDescriptionFlags2`, `SpellDescriptionFlags3`, `SpellDescriptionFlags4`, `SpellDescriptionFlags5`, `SpellDescriptionFlags6`, `SpellDescriptionFlags7`, `SpellToolTip0`, `SpellToolTip1`, `SpellToolTip2`, `SpellToolTip3`, `SpellToolTip4`, `SpellToolTip5`, `SpellToolTip6`, `SpellToolTip7`, `SpellToolTip8`, `SpellToolTipFlags0`, `SpellToolTipFlags1`, `SpellToolTipFlags2`, `SpellToolTipFlags3`, `SpellToolTipFlags4`, `SpellToolTipFlags5`, `SpellToolTipFlags6`, `SpellToolTipFlags7`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaximumTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `MaximumAffectedTargets`, `DamageClass`, `PreventionType`, `StanceBarOrder`, `EffectDamageMultiplier1`, `EffectDamageMultiplier2`, `EffectDamageMultiplier3`, `MinimumFactionId`, `MinimumReputation`, `RequiredAuraVision`, `TotemCategory1`, `TotemCategory2`, `AreaGroupID`, `SchoolMask`, `RuneCostID`, `SpellMissileID`, `PowerDisplayId`, `EffectBonusMultiplier1`, `EffectBonusMultiplier2`, `EffectBonusMultiplier3`, `SpellDescriptionVariableID`, `SpellDifficultyID`) VALUES
(200522, 0, 0, 0, 464, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 327680, 100, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 0, 0, 1, 0, 0, 0, 0, 0, 19, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 113, 0, 0, 'Malfeasance', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Rank 2', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Damage from your Drain Life, Shadow Bolt and Haunt has a $s1% chance to clear a stack of Mark of Gul''dan.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712190, 'Damage from your Drain Life, Shadow Bolt and Haunt has a $s1% chance to clear a stack of Mark of Gul''dan.', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 16712188, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 1, 1, 1, 0, 0);

-- ============================================================
-- spell_proc: Drain Life / Shadow Bolt / Haunt, 10% and 20%
-- ============================================================
-- SpellFamilyName 5 (Warlock).
--   SpellFamilyMask0 9       = 0x1 Shadow Bolt | 0x8 Drain Life
--   SpellFamilyMask1 262144  = 0x40000 Haunt
-- ProcFlags 327680 = 0x50000 = DONE_SPELL_MAGIC_DMG_CLASS_NEG | DONE_PERIODIC.
-- DONE_PERIODIC covers Drain Life, which does its damage as channel ticks;
-- Shadow Bolt and Haunt are direct hits and use the other half.
--
-- The 10/20% roll lives here, one row per rank, so the AuraScript is
-- unconditional.  SpellPhaseMask 2 is mandatory -- a zero phase mask makes
-- the proc silently never fire.

DELETE FROM `spell_proc` WHERE `SpellId` IN (200521, 200522);
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(200521, 0, 5, 9, 262144, 0, 327680, 1, 2, 0, 0, 0, 0, 10, 0, 0),
(200522, 0, 5, 9, 262144, 0, 327680, 1, 2, 0, 0, 0, 0, 20, 0, 0);


-- ============================================================
-- Script registration
-- ============================================================
-- Both ranks share one script; the rank difference is entirely the
-- spell_proc Chance column.

DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_warl_malfeasance';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(200521, 'spell_warl_malfeasance'),
(200522, 'spell_warl_malfeasance');


-- ============================================================
-- talent_dbc: NEW talent 3004, gated on Fel Interdiction
-- ============================================================
-- Tier 8 Col 3 is empty in the stock Affliction tree and sits directly below
-- Fel Interdiction's new home at Tier 7 Col 3, so the prereq arrow is a clean
-- vertical.
--
-- PrereqTalent_1 = 1668, PrereqRank_1 = 0.  PrereqRank_1 is ZERO-INDEXED --
-- 0 means "rank 1 required".  Fel Interdiction is a 1-point talent, so
-- writing 1 here would demand a rank 2 that does not exist and leave
-- Malfeasance permanently unlearnable.  Same pattern as Pandemic (2245),
-- which gates on the 1-point Unstable Affliction with PrereqRank_1 = 0.
-- Flags = 0: passive, must not be added to the spellbook.
--
-- Record ordering is not a concern -- build_dbc.py re-sorts by
-- (TabID, TierID, ColumnIndex), which is what the client requires; appending
-- a new record in ID order would blank the entire tree.

DELETE FROM `talent_dbc` WHERE `ID` = 3004;
INSERT INTO `talent_dbc` (
    `ID`, `TabID`, `TierID`, `ColumnIndex`,
    `SpellRank_1`, `SpellRank_2`, `SpellRank_3`, `SpellRank_4`, `SpellRank_5`,
    `SpellRank_6`, `SpellRank_7`, `SpellRank_8`, `SpellRank_9`,
    `PrereqTalent_1`, `PrereqTalent_2`, `PrereqTalent_3`,
    `PrereqRank_1`, `PrereqRank_2`, `PrereqRank_3`,
    `Flags`, `RequiredSpellID`, `CategoryMask_1`, `CategoryMask_2`
) VALUES (
    3004, 302, 8, 3,
    200521, 200522, 0, 0, 0,
    0, 0, 0, 0,
    1668, 0, 0,
    0, 0, 0,
    0, 0, 0, 0
);
