/*
 * Item upgrade tools.
 *
 * Artificer Volen sells 16 consumables, one per target level (5, 10 ... 80).
 * Using one gives the item-targeting cursor -- the same interaction as a
 * sharpening stone -- and clicking an item reforges it to that tool's level.
 *
 * Why this shape rather than a gossip menu:
 *   * The price and the shop UI are plain `npc_vendor` data, so there is no
 *     gold handling and no menu paging code to get wrong.
 *   * The player points at the item instead of picking it out of a 19-line list.
 *
 * Spells and items are generated by tools/gen_upgrade_tools.py.  The target
 * level is carried in the spell's MaximumLevel field so this file needs no
 * hardcoded id-to-level table.
 *
 * The bag path is trivial (destroy, store).  The equipped path is not, and its
 * ordering is load-bearing -- see the comment on UpgradeEquipped.
 *
 * Both paths have a second route for items that block their own replacement:
 * see IsSelfConflict and UpgradeEquippedDestroyFirst.
 */

#include "Chat.h"
#include "EventProcessor.h"
#include "Item.h"
#include "ItemUpgrade.h"
#include "ItemUpgradeAffix.h"
#include "Log.h"
#include "ObjectMgr.h"
#include "Player.h"
#include "ScriptMgr.h"
#include "SharedDefines.h"
#include "SpellScript.h"
#include "StringFormat.h"

#include <array>

namespace
{
    using namespace Alonecraft::ItemUpgrade;

    struct Carried
    {
        std::array<uint32, MAX_INSPECTED_ENCHANTMENT_SLOT> enchantId{};
        std::array<uint32, MAX_INSPECTED_ENCHANTMENT_SLOT> enchantDuration{};
        std::array<uint32, MAX_INSPECTED_ENCHANTMENT_SLOT> enchantCharges{};
        int32 randomProp = 0;
        ObjectGuid creator;
        uint32 playedTime = 0;
        bool soulbound = false;
    };

    Carried Snapshot(Item* item)
    {
        Carried c;
        for (uint8 i = 0; i < MAX_INSPECTED_ENCHANTMENT_SLOT; ++i)
        {
            EnchantmentSlot es = EnchantmentSlot(i);
            c.enchantId[i] = item->GetEnchantmentId(es);
            c.enchantDuration[i] = item->GetEnchantmentDuration(es);
            c.enchantCharges[i] = item->GetEnchantmentCharges(es);
        }
        c.randomProp = item->GetItemRandomPropertyId();
        c.creator = item->GetGuidValue(ITEM_FIELD_CREATOR);
        c.playedTime = item->GetUInt32Value(ITEM_FIELD_CREATE_PLAYED_TIME);
        c.soulbound = item->IsSoulBound();
        return c;
    }

    // retier = false is the rollback case: the item being re-created IS the
    // original, so its affix must stay on the tier it already had.
    void Restore(Player* player, Item* neo, Carried const& c,
                 ItemTemplate const* proto, bool retier = true)
    {
        neo->SetUInt32Value(ITEM_FIELD_CREATE_PLAYED_TIME, c.playedTime);

        // Random properties FIRST: SetItemRandomProperties writes enchantment
        // slots 7..11 itself and recomputes the suffix magnitude from the NEW
        // template's ItemLevel (ItemEnchantmentMgr.cpp:134), which is how an
        // "of the Bear" suffix rescales itself for free.
        //
        // That free rescale only covers RandomSuffix items -- roughly half of
        // them.  A vanilla RandomProperty is a fixed enchantment picked from a
        // per-slot ladder, so it has to be walked up the ladder explicitly or
        // the level-80 variant still reads "+5 Intellect".
        if (c.randomProp)
            neo->SetItemRandomProperties(
                retier ? RetierRandomProperty(c.randomProp, proto->RandomProperty)
                       : c.randomProp);

        // Slots 0..6 only -- 7..11 belong to the call above.
        for (uint8 i = 0; i < MAX_INSPECTED_ENCHANTMENT_SLOT; ++i)
            if (c.enchantId[i])
                neo->SetEnchantment(EnchantmentSlot(i), c.enchantId[i],
                                    c.enchantDuration[i], c.enchantCharges[i]);

        if (c.soulbound || proto->Bonding == BIND_WHEN_PICKED_UP ||
            proto->Bonding == BIND_WHEN_EQUIPPED || proto->Bonding == BIND_WHEN_USE)
            neo->SetBinding(true);

        neo->SetNotRefundable(player);
        neo->ClearSoulboundTradeable(player);

        // AFTER ClearSoulboundTradeable, which zeroes ITEM_FIELD_CREATOR itself.
        // Setting it earlier looked correct and was silently undone.
        neo->SetGuidValue(ITEM_FIELD_CREATOR, c.creator);
    }

    void Say(Player* player, std::string const& text)
    {
        ChatHandler(player->GetSession()).PSendSysMessage("{}", text);
    }

    // Errors an item can inflict on its OWN replacement.
    //
    // Player::CanEquipItem calls CanTakeMoreSimilarItems unconditionally at
    // PlayerStorage.cpp:1918, BEFORE the swap-aware CanEquipUniqueItem at
    // :2005.  CanTakeMoreSimilarItems (:803, limit-category block :832-852) has
    // no swap or except-slot parameter at all -- GetItemCountWithLimitCategory
    // skips only the item handed to it, which is the NEW one -- so the base item
    // counts against its own upgrade and the player is told "You can only carry
    // 1 <family>".  Every one of the 593 synthetic ItemLimitCategory families
    // that closes the base+variant dupe reopens as this bug: 1442 variants
    // across 307 base items.
    //
    // CanStoreNewItem reaches the same check via CanStoreItem (:1171), so the
    // bag path fails identically.
    //
    // These are therefore "maybe", not "no".  They are resolved by asking the
    // core again once the base is genuinely gone -- never by deciding here that
    // the conflict was self-inflicted.  Working that out in the module means
    // reimplementing GetItemCountWithLimitCategory (equipped + keyring + bags +
    // bank + socketed gems) and keeping it in sync with core; erring permissive
    // reopens the very dupe the categories exist to close.
    //
    // Only the ItemLimitCategory errors qualify.  EQUIP_ERR_CANT_CARRY_MORE_OF_
    // THIS (the MaxCount branch, :821) and EQUIP_ERR_ITEM_UNIQUE_EQUIPABLE
    // (HasItemOrGemWithIdEquipped, Player.cpp:13980) are both keyed on the item
    // ID being added -- the variant's, never the base's -- so they can only mean
    // a genuine second copy, and destroying the base would not help.
    bool IsSelfConflict(InventoryResult res)
    {
        switch (res)
        {
            case EQUIP_ERR_ITEM_MAX_LIMIT_CATEGORY_COUNT_EXCEEDED:
            case EQUIP_ERR_ITEM_MAX_LIMIT_CATEGORY_EQUIPPED_EXCEEDED:
            case EQUIP_ERR_ITEM_MAX_COUNT_EQUIPPED_SOCKETED:
                return true;
            default:
                return false;
        }
    }

    // The base is already destroyed by the time this runs, so rolling back means
    // re-creating it.  Everything worth keeping is in `carried`; what cannot be
    // recovered (item GUID, refund eligibility, the BoP trade window, worn
    // durability) is lost on the success path too.
    //
    // Ladder: the slot we just emptied, then the bags, then the mailbox.  The
    // last rung is not decoration -- the destroy-first path can be entered with
    // full bags, and without it a failed equip would destroy the item outright.
    void Rollback(Player* player, uint8 slot, uint32 baseEntry,
                  ItemTemplate const* baseProto, Carried const& carried)
    {
        uint16 dest = 0;
        if (slot != NULL_SLOT &&
            player->CanEquipNewItem(slot, dest, baseEntry, false) == EQUIP_ERR_OK)
            if (Item* back = player->EquipNewItem(dest, baseEntry, true))
            {
                Restore(player, back, carried, baseProto, false);
                player->ApplyEnchantment(back, true);
                player->ToggleMetaGemsActive(slot, true);
                Say(player, "The reforge failed; your item is unchanged.");
                return;
            }

        ItemPosCountVec bagDest;
        if (player->CanStoreNewItem(NULL_BAG, NULL_SLOT, bagDest, baseEntry, 1)
            == EQUIP_ERR_OK)
            if (Item* back = player->StoreNewItem(bagDest, baseEntry, true))
            {
                Restore(player, back, carried, baseProto, false);
                back->SetState(ITEM_CHANGED, player);
                Say(player, "The reforge failed; your item is in your bags.");
                return;
            }

        if (Item* back = Item::CreateItem(baseEntry, 1, player))
        {
            Restore(player, back, carried, baseProto, false);
            player->SendItemRetrievalMail(back);
            Say(player, "The reforge failed; your item has been mailed to you.");
            return;
        }

        LOG_DEBUG("alonecraft.debug",
                  "ItemUpgrade: rollback of entry {} for {} recovered nothing",
                  baseEntry, player->GetGUID().ToString());
        Say(player, "The reforge failed and your item could not be recovered. "
                    "Please contact a game master.");
    }

    // Somewhere to put a bagged replacement: the slot the original occupies
    // first, then anywhere.  The original slot can be refused by a bag-specific
    // restriction (an ammo pouch, say), which is what the fallback is for.
    InventoryResult FindBagSpace(Player* player, uint8 bag, uint8 slot,
                                 ItemPosCountVec& dest, uint32 newEntry)
    {
        dest.clear();
        InventoryResult msg = player->CanStoreNewItem(bag, slot, dest, newEntry, 1);
        if (msg == EQUIP_ERR_OK)
            return msg;

        dest.clear();
        return player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, newEntry, 1);
    }

    // Item sitting in a bag: destroy it and store the replacement.  Both are
    // ordinary operations and no equipment slot is involved.
    bool UpgradeInBag(Player* player, Item* item, uint32 newEntry, ItemTemplate const* proto)
    {
        uint8 bag = item->GetBagSlot();
        uint8 slot = item->GetSlot();

        ItemPosCountVec dest;
        InventoryResult msg = FindBagSpace(player, bag, slot, dest, newEntry);
        if (msg != EQUIP_ERR_OK && !IsSelfConflict(msg))
        {
            player->SendEquipError(msg, item, nullptr, newEntry);
            return false;
        }

        // Anything read off `item` must be read NOW.  Player::DestroyItem ends
        // in Item::SetState(ITEM_REMOVED), which for an ITEM_NEW item is
        // `delete this` (Item.cpp:714-726) -- the pointer can be dangling the
        // instant it returns.  The ItemTemplate is owned by ObjectMgr and
        // outlives the item, so caching that is safe.
        uint32 baseEntry = item->GetEntry();
        ItemTemplate const* baseProto = item->GetTemplate();
        Carried carried = Snapshot(item);
        bool selfConflict = msg != EQUIP_ERR_OK;

        player->DestroyItem(bag, slot, true);

        // Re-ask now the base is gone.  The freed slot guarantees room, so only
        // the uniqueness verdict can have changed -- and if it has not, the
        // conflict was real (a legacy duplicate, say) and we put the item back.
        if (selfConflict &&
            FindBagSpace(player, bag, slot, dest, newEntry) != EQUIP_ERR_OK)
        {
            Rollback(player, NULL_SLOT, baseEntry, baseProto, carried);
            return false;
        }

        Item* neo = player->StoreNewItem(dest, newEntry, true);
        if (!neo)
        {
            Rollback(player, NULL_SLOT, baseEntry, baseProto, carried);
            return false;
        }

        Restore(player, neo, carried, proto);
        neo->SetState(ITEM_CHANGED, player);
        return true;
    }

    // The normal equipped path: park the old item in a bag, equip the
    // replacement into the now-EMPTY slot, destroy the parked original last.
    // Destroying last means a failure anywhere loses nothing but the tool.
    //
    // The CanStoreItem/RemoveItem/StoreItem trio is lifted from
    // Player::AutoUnequipOffhandIfNeed (Player.cpp:12583-12588).
    bool UpgradeEquippedParked(Player* player, Item* item, uint8 slot, uint16 dest,
                               ItemPosCountVec const& parkPos, uint32 newEntry,
                               ItemTemplate const* proto)
    {
        Carried carried = Snapshot(item);

        player->RemoveItem(INVENTORY_SLOT_BAG_0, slot, true);
        Item* parked = player->StoreItem(parkPos, item, true);

        // Third argument is `update`, not swap -- by here the slot really is
        // empty, so no swap semantics are needed.
        Item* neo = player->EquipNewItem(dest, newEntry, true);
        if (!neo)
        {
            // The original is parked in the bags, not destroyed.  Say so, or it
            // reads as the item having vanished.
            Say(player, "Could not equip the reforged item; your original is in "
                        "your bags.");
            return false;
        }

        if (parked)
            player->DestroyItem(parked->GetBagSlot(), parked->GetSlot(), true);

        Restore(player, neo, carried, proto);
        player->ApplyEnchantment(neo, true);
        player->ToggleMetaGemsActive(slot, true);
        return true;
    }

    // The path for an item that blocks its own replacement -- see
    // IsSelfConflict.  Parking cannot help here: a parked base still counts
    // against its own ItemLimitCategory, because CanTakeMoreSimilarItems
    // (PlayerStorage.cpp:832-852) counts bags as readily as equipment slots.
    // The base has to actually be gone.
    //
    // Destroy-first is safe here, and the reason the old comment said otherwise
    // is worth recording.  Two hazards, both real:
    //
    //   * Item::SetState(ITEM_REMOVED) on an ITEM_NEW item is `delete this`
    //     (Item.cpp:714-726), and Player::DestroyItem ends in exactly that
    //     (PlayerStorage.cpp:3208).  Run from inside the spell effect, where
    //     Spell::itemTarget still holds the pointer, that is a use-after-free.
    //   * EquipNewItem's third argument is `update`, NOT swap.  Into an
    //     occupied slot, EquipItem takes its stacking branch
    //     (PlayerStorage.cpp:2898-2925), deletes the new item and returns the
    //     OLD one -- so a caller that then "destroys the old one" leaves
    //     m_items[slot] dangling.
    //
    // Either leaves a freed pointer in m_itemUpdateQueue, which _SaveInventory
    // dereferences at PlayerStorage.cpp:7477 -- inside SaveToDB, hence the data
    // loss.  Destroy-first was never the problem; destroy-while-still-
    // referenced was.  This function runs from UpgradeEquippedEvent, one tick
    // after Spell::finish(), touches `item` only before the destroy, and equips
    // into a slot that is genuinely empty with swap = false.
    bool UpgradeEquippedDestroyFirst(Player* player, Item* item, uint8 slot,
                                     uint32 newEntry, ItemTemplate const* proto)
    {
        uint32 baseEntry = item->GetEntry();
        ItemTemplate const* baseProto = item->GetTemplate();
        Carried carried = Snapshot(item);

        player->DestroyItem(INVENTORY_SLOT_BAG_0, slot, true);
        // `item` is dangling from here on.  Do not touch it.

        uint16 dest = 0;
        InventoryResult canEquip = player->CanEquipNewItem(slot, dest, newEntry, false);
        if (canEquip == EQUIP_ERR_OK)
            if (Item* neo = player->EquipNewItem(dest, newEntry, true))
            {
                Restore(player, neo, carried, proto);
                player->ApplyEnchantment(neo, true);
                player->ToggleMetaGemsActive(slot, true);
                return true;
            }

        // The core still says no with the base gone, so the conflict was real --
        // a duplicate acquired before the limit categories were applied, most
        // likely.  Put the original back.
        LOG_DEBUG("alonecraft.debug",
                  "ItemUpgrade: {} -> {} rejected post-destroy with {}",
                  baseEntry, newEntry, static_cast<uint32>(canEquip));
        Rollback(player, slot, baseEntry, baseProto, carried);
        return false;
    }

    // Item currently worn.  Two routes, and the ordinary one is unchanged: the
    // destroy-first fallback is entered only where the parked route would have
    // failed outright, so it cannot regress anything that works today.
    bool UpgradeEquipped(Player* player, Item* item, uint8 slot,
                         uint32 newEntry, ItemTemplate const* proto)
    {
        ItemPosCountVec parkPos;
        InventoryResult canPark = player->CanStoreItem(NULL_BAG, NULL_SLOT, parkPos,
                                                       item, false);

        // swap = TRUE, and it is load-bearing twice over.  This check runs while
        // the old item is still worn -- deliberately, so a failure costs nothing
        // -- and CanEquipItem interprets swap as "the slot is about to be freed":
        //
        //   * PlayerStorage.cpp:1972 rejects an occupied slot outright unless
        //     swap is set, which failed EVERY equipped upgrade with
        //     EQUIP_ERR_NO_EQUIPMENT_SLOT_AVAILABLE.
        //   * CanEquipUniqueItem (PlayerStorage.cpp:2005) only ignores the item
        //     being replaced when swap is set.
        //
        // What swap does NOT reach is CanTakeMoreSimilarItems, called earlier and
        // unconditionally at :1918 -- see IsSelfConflict.
        uint16 dest = 0;
        InventoryResult canEquip = player->CanEquipNewItem(slot, dest, newEntry, true);

        if (canEquip == EQUIP_ERR_OK && canPark == EQUIP_ERR_OK)
            return UpgradeEquippedParked(player, item, slot, dest, parkPos,
                                         newEntry, proto);

        if (IsSelfConflict(canEquip))
            return UpgradeEquippedDestroyFirst(player, item, slot, newEntry, proto);

        if (canEquip != EQUIP_ERR_OK)
            player->SendEquipError(canEquip, nullptr, nullptr, newEntry);
        else
            player->SendEquipError(canPark, item, nullptr);
        return false;
    }

    // Equipping cannot happen inside the tool's own spell effect.
    //
    // Player::CanEquipItem ends its runtime block with
    //
    //     if (IsNonMeleeSpellCast(false))
    //         return EQUIP_ERR_CANT_DO_RIGHT_NOW;      // PlayerStorage.cpp:1952
    //
    // and the spell being cast IS the tool.  The check is a false positive by
    // construction: it can never pass while the effect handler is running, so
    // the equipped path failed every time -- after the charge had already been
    // taken, because Spell::TakeCastItem does not care whether the effects did
    // anything.
    //
    // Deferring by one tick lets Spell::finish() clear the current spell first.
    // Everything is revalidated on the way in, since a tick is long enough for
    // the player to have moved the item.
    class UpgradeEquippedEvent : public BasicEvent
    {
    public:
        UpgradeEquippedEvent(Player* player, ObjectGuid itemGuid, uint32 newEntry)
            : _player(player), _itemGuid(itemGuid), _newEntry(newEntry) { }

        bool Execute(uint64, uint32) override
        {
            Item* item = _player->GetItemByGuid(_itemGuid);
            ItemTemplate const* proto = sObjectMgr->GetItemTemplate(_newEntry);
            if (!item || !item->IsEquipped() || !proto)
            {
                Say(_player, "The reforge could not be completed.");
                return true;
            }

            std::string oldName = item->GetTemplate()->Name1;
            if (UpgradeEquipped(_player, item, item->GetSlot(), _newEntry, proto))
                Say(_player, Acore::StringFormat("{} reforged to level {}.",
                                                 oldName, proto->RequiredLevel));
            return true;
        }

    private:
        Player* _player;
        ObjectGuid _itemGuid;
        uint32 _newEntry;
    };
}

class spell_item_upgrade_tool : public SpellScript
{
    PrepareSpellScript(spell_item_upgrade_tool);

    // Target level travels in the spell's MaximumLevel, set by
    // tools/gen_upgrade_tools.py, so there is no id-to-level table to drift.
    // Not const: SpellScript::GetSpellInfo() is a non-const member.
    uint8 TargetLevel()
    {
        return static_cast<uint8>(GetSpellInfo()->MaxLevel);
    }

    // Runs before the tool is consumed, so a rejected upgrade costs nothing.
    SpellCastResult CheckCast()
    {
        // GetHitItem() is only populated during effect handling; in CheckCast
        // the explicitly-targeted item is the one the player clicked.
        Player* player = GetCaster() ? GetCaster()->ToPlayer() : nullptr;
        Item* item = GetExplTargetItem();
        if (!player || !item)
            return SPELL_FAILED_BAD_TARGETS;

        if (!IsEnabled())
        {
            Say(player, "Item upgrades are currently disabled.");
            return SPELL_FAILED_DONT_REPORT;
        }

        uint8 target = TargetLevel();
        if (player->GetLevel() < target)
        {
            Say(player, Acore::StringFormat(
                "You must be level {} to use this.", target));
            return SPELL_FAILED_DONT_REPORT;
        }

        auto [baseEntry, step] = Decode(item->GetEntry());
        uint32 newEntry = 0;
        ItemTemplate const* proto = FindVariantAtLevel(baseEntry, target, newEntry);
        if (!proto)
        {
            Say(player, Acore::StringFormat(
                "{} has no reforged form at level {} or below.",
                item->GetTemplate()->Name1, target));
            return SPELL_FAILED_DONT_REPORT;
        }

        if (proto->RequiredLevel <= item->GetTemplate()->RequiredLevel)
        {
            Say(player, "That item is already at least this powerful.");
            return SPELL_FAILED_DONT_REPORT;
        }

        if (item->IsInTrade())
            return SPELL_FAILED_ITEM_NOT_READY;

        // A replacement arrives at full durability, so upgrading a broken item
        // would be a cut-price repair.
        if (item->GetTemplate()->MaxDurability > 0 &&
            item->GetUInt32Value(ITEM_FIELD_DURABILITY) == 0)
        {
            Say(player, "Repair that item before reforging it.");
            return SPELL_FAILED_DONT_REPORT;
        }

        // Reject a genuinely impossible upgrade here rather than a tick later,
        // when the tool has already been consumed.  A self-conflict is expected
        // and is resolved downstream, so it must pass.
        //
        // CanTakeMoreSimilarItems and not CanEquipNewItem: CanEquipItem ends its
        // runtime block with IsNonMeleeSpellCast(false) (PlayerStorage.cpp:1951),
        // which is true throughout CheckCast because the spell being cast IS the
        // tool -- the same false positive documented on UpgradeEquippedEvent.
        InventoryResult similar = player->CanTakeMoreSimilarItems(newEntry, 1);
        if (similar != EQUIP_ERR_OK && !IsSelfConflict(similar))
        {
            player->SendEquipError(similar, nullptr, nullptr, newEntry);
            return SPELL_FAILED_DONT_REPORT;
        }

        return SPELL_CAST_OK;
    }

    void HandleUpgrade(SpellEffIndex /*effIndex*/)
    {
        Player* player = GetCaster() ? GetCaster()->ToPlayer() : nullptr;
        Item* item = GetHitItem();
        if (!player || !item)
            return;

        auto [baseEntry, step] = Decode(item->GetEntry());
        uint32 newEntry = 0;
        ItemTemplate const* proto = FindVariantAtLevel(baseEntry, TargetLevel(), newEntry);
        if (!proto)
            return;

        if (item->IsEquipped())
        {
            // Deferred to the next tick -- see UpgradeEquippedEvent for why the
            // equip cannot happen while this spell is still being cast.  Keyed
            // by GUID rather than by pointer or slot, both of which a tick can
            // invalidate.
            player->m_Events.AddEvent(
                new UpgradeEquippedEvent(player, item->GetGUID(), newEntry),
                player->m_Events.CalculateTime(1));
            return;
        }

        std::string oldName = item->GetTemplate()->Name1;
        if (UpgradeInBag(player, item, newEntry, proto))
            Say(player, Acore::StringFormat("{} reforged to level {}.",
                                            oldName, proto->RequiredLevel));
    }

    void Register() override
    {
        OnCheckCast += SpellCheckCastFn(spell_item_upgrade_tool::CheckCast);
        OnEffectHitTarget += SpellEffectFn(spell_item_upgrade_tool::HandleUpgrade,
                                           EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
    }
};

void AddSC_item_upgrade_tool()
{
    RegisterSpellScript(spell_item_upgrade_tool);
}
