/*
 * Item upgrade tools.
 *
 * Artificer Volen sells 16 consumables, one per target level (5, 10 ... 80).
 * Using one gives the item-targeting cursor -- the same interaction as a
 * sharpening stone -- and clicking an item reforges it to that tool's level.
 *
 * Why this shape rather than a gossip menu:
 *   * The price and the shop UI are plain `npc_vendor` data, so there is no
 *     gold handling and no menu paging code to get wrong.
 *   * The player points at the item instead of picking it out of a 19-line list.
 *
 * Spells and items are generated by tools/gen_upgrade_tools.py.  The target
 * level is carried in the spell's MaximumLevel field so this file needs no
 * hardcoded id-to-level table.
 *
 * The bag path is trivial (destroy, store).  The equipped path is not, and its
 * ordering is load-bearing -- see the comment on UpgradeEquipped.
 */

#include "Chat.h"
#include "EventProcessor.h"
#include "Item.h"
#include "ItemUpgrade.h"
#include "ItemUpgradeAffix.h"
#include "ObjectMgr.h"
#include "Player.h"
#include "ScriptMgr.h"
#include "SharedDefines.h"
#include "SpellScript.h"
#include "StringFormat.h"

#include <array>

namespace
{
    using namespace Alonecraft::ItemUpgrade;

    struct Carried
    {
        std::array<uint32, MAX_INSPECTED_ENCHANTMENT_SLOT> enchantId{};
        std::array<uint32, MAX_INSPECTED_ENCHANTMENT_SLOT> enchantDuration{};
        std::array<uint32, MAX_INSPECTED_ENCHANTMENT_SLOT> enchantCharges{};
        int32 randomProp = 0;
        ObjectGuid creator;
        uint32 playedTime = 0;
        bool soulbound = false;
    };

    Carried Snapshot(Item* item)
    {
        Carried c;
        for (uint8 i = 0; i < MAX_INSPECTED_ENCHANTMENT_SLOT; ++i)
        {
            EnchantmentSlot es = EnchantmentSlot(i);
            c.enchantId[i] = item->GetEnchantmentId(es);
            c.enchantDuration[i] = item->GetEnchantmentDuration(es);
            c.enchantCharges[i] = item->GetEnchantmentCharges(es);
        }
        c.randomProp = item->GetItemRandomPropertyId();
        c.creator = item->GetGuidValue(ITEM_FIELD_CREATOR);
        c.playedTime = item->GetUInt32Value(ITEM_FIELD_CREATE_PLAYED_TIME);
        c.soulbound = item->IsSoulBound();
        return c;
    }

    void Restore(Player* player, Item* neo, Carried const& c, ItemTemplate const* proto)
    {
        neo->SetUInt32Value(ITEM_FIELD_CREATE_PLAYED_TIME, c.playedTime);

        // Random properties FIRST: SetItemRandomProperties writes enchantment
        // slots 7..11 itself and recomputes the suffix magnitude from the NEW
        // template's ItemLevel (ItemEnchantmentMgr.cpp:134), which is how an
        // "of the Bear" suffix rescales itself for free.
        //
        // That free rescale only covers RandomSuffix items -- roughly half of
        // them.  A vanilla RandomProperty is a fixed enchantment picked from a
        // per-slot ladder, so it has to be walked up the ladder explicitly or
        // the level-80 variant still reads "+5 Intellect".
        if (c.randomProp)
            neo->SetItemRandomProperties(
                RetierRandomProperty(c.randomProp, proto->RandomProperty));

        // Slots 0..6 only -- 7..11 belong to the call above.
        for (uint8 i = 0; i < MAX_INSPECTED_ENCHANTMENT_SLOT; ++i)
            if (c.enchantId[i])
                neo->SetEnchantment(EnchantmentSlot(i), c.enchantId[i],
                                    c.enchantDuration[i], c.enchantCharges[i]);

        if (c.soulbound || proto->Bonding == BIND_WHEN_PICKED_UP ||
            proto->Bonding == BIND_WHEN_EQUIPPED || proto->Bonding == BIND_WHEN_USE)
            neo->SetBinding(true);

        neo->SetNotRefundable(player);
        neo->ClearSoulboundTradeable(player);

        // AFTER ClearSoulboundTradeable, which zeroes ITEM_FIELD_CREATOR itself.
        // Setting it earlier looked correct and was silently undone.
        neo->SetGuidValue(ITEM_FIELD_CREATOR, c.creator);
    }

    void Say(Player* player, std::string const& text)
    {
        ChatHandler(player->GetSession()).PSendSysMessage("{}", text);
    }

    // Item sitting in a bag: destroy it and store the replacement.  Both are
    // ordinary operations and no equipment slot is involved.
    bool UpgradeInBag(Player* player, Item* item, uint32 newEntry, ItemTemplate const* proto)
    {
        ItemPosCountVec dest;
        InventoryResult msg = player->CanStoreNewItem(item->GetBagSlot(), item->GetSlot(),
                                                      dest, newEntry, 1);
        if (msg != EQUIP_ERR_OK)
        {
            // Fall back to anywhere in the bags -- the original slot may be
            // reserved by a bag-specific restriction (e.g. an ammo pouch).
            msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, newEntry, 1);
            if (msg != EQUIP_ERR_OK)
            {
                player->SendEquipError(msg, item, nullptr, newEntry);
                return false;
            }
        }

        Carried carried = Snapshot(item);
        player->DestroyItem(item->GetBagSlot(), item->GetSlot(), true);

        Item* neo = player->StoreNewItem(dest, newEntry, true);
        if (!neo)
            return false;

        Restore(player, neo, carried, proto);
        neo->SetState(ITEM_CHANGED, player);
        return true;
    }

    // Item currently worn.  The old item is unequipped into a bag first and the
    // replacement equipped into an EMPTY slot.
    //
    // The obvious alternative -- DestroyItem then EquipNewItem(swap=true) into
    // the same slot -- crashed the server: Player::_SaveInventory faulted on
    // logout (PlayerStorage.cpp:7477), inside SaveToDB, making it a data-loss
    // bug rather than merely a stability one.  Nothing in core replaces an
    // equipped item that way; every EquipNewItem call site targets an empty
    // slot.  The CanStoreItem/RemoveItem/StoreItem trio below is lifted from
    // Player::AutoUnequipOffhandIfNeed (Player.cpp:12583-12588).
    bool UpgradeEquipped(Player* player, Item* item, uint8 slot,
                         uint32 newEntry, ItemTemplate const* proto)
    {
        ItemPosCountVec parkPos;
        InventoryResult canPark = player->CanStoreItem(NULL_BAG, NULL_SLOT, parkPos, item, false);
        if (canPark != EQUIP_ERR_OK)
        {
            player->SendEquipError(canPark, item, nullptr);
            return false;
        }

        // swap = TRUE, and it is load-bearing twice over.  This check runs while
        // the old item is still worn -- deliberately, so a failure costs nothing
        // -- and CanEquipItem interprets swap as "the slot is about to be freed":
        //
        //   * PlayerStorage.cpp:1972 rejects an occupied slot outright unless
        //     swap is set, which failed EVERY equipped upgrade with
        //     EQUIP_ERR_NO_EQUIPMENT_SLOT_AVAILABLE.
        //   * CanEquipUniqueItem (PlayerStorage.cpp:2005) only ignores the item
        //     being replaced when swap is set.  Without it the base item's own
        //     ItemLimitCategory -- the 593 synthetic families that close the
        //     unique-equipped dupe -- counts against its own replacement.
        //
        // Both were invisible in the bag path, which never touches an equipment
        // slot, which is why this survived the bag-first test order.
        uint16 dest = 0;
        InventoryResult canEquip = player->CanEquipNewItem(slot, dest, newEntry, true);
        if (canEquip != EQUIP_ERR_OK)
        {
            player->SendEquipError(canEquip, nullptr, nullptr, newEntry);
            return false;
        }

        Carried carried = Snapshot(item);

        player->RemoveItem(INVENTORY_SLOT_BAG_0, slot, true);
        Item* parked = player->StoreItem(parkPos, item, true);

        // Third argument is `update`, not swap -- by here the slot really is
        // empty, so no swap semantics are needed.
        Item* neo = player->EquipNewItem(dest, newEntry, true);
        if (!neo)
        {
            // The original is parked in the bags, not destroyed: destruction is
            // deliberately the last step so this path loses nothing but the
            // tool.  Say so, or it reads as the item having vanished.
            Say(player, "Could not equip the reforged item; your original is in "
                        "your bags.");
            return false;
        }

        if (parked)
            player->DestroyItem(parked->GetBagSlot(), parked->GetSlot(), true);

        Restore(player, neo, carried, proto);
        player->ApplyEnchantment(neo, true);
        player->ToggleMetaGemsActive(slot, true);
        return true;
    }

    // Equipping cannot happen inside the tool's own spell effect.
    //
    // Player::CanEquipItem ends its runtime block with
    //
    //     if (IsNonMeleeSpellCast(false))
    //         return EQUIP_ERR_CANT_DO_RIGHT_NOW;      // PlayerStorage.cpp:1952
    //
    // and the spell being cast IS the tool.  The check is a false positive by
    // construction: it can never pass while the effect handler is running, so
    // the equipped path failed every time -- after the charge had already been
    // taken, because Spell::TakeCastItem does not care whether the effects did
    // anything.
    //
    // Deferring by one tick lets Spell::finish() clear the current spell first.
    // Everything is revalidated on the way in, since a tick is long enough for
    // the player to have moved the item.
    class UpgradeEquippedEvent : public BasicEvent
    {
    public:
        UpgradeEquippedEvent(Player* player, ObjectGuid itemGuid, uint32 newEntry)
            : _player(player), _itemGuid(itemGuid), _newEntry(newEntry) { }

        bool Execute(uint64, uint32) override
        {
            Item* item = _player->GetItemByGuid(_itemGuid);
            ItemTemplate const* proto = sObjectMgr->GetItemTemplate(_newEntry);
            if (!item || !item->IsEquipped() || !proto)
            {
                Say(_player, "The reforge could not be completed.");
                return true;
            }

            std::string oldName = item->GetTemplate()->Name1;
            if (UpgradeEquipped(_player, item, item->GetSlot(), _newEntry, proto))
                Say(_player, Acore::StringFormat("{} reforged to level {}.",
                                                 oldName, proto->RequiredLevel));
            return true;
        }

    private:
        Player* _player;
        ObjectGuid _itemGuid;
        uint32 _newEntry;
    };
}

class spell_item_upgrade_tool : public SpellScript
{
    PrepareSpellScript(spell_item_upgrade_tool);

    // Target level travels in the spell's MaximumLevel, set by
    // tools/gen_upgrade_tools.py, so there is no id-to-level table to drift.
    // Not const: SpellScript::GetSpellInfo() is a non-const member.
    uint8 TargetLevel()
    {
        return static_cast<uint8>(GetSpellInfo()->MaxLevel);
    }

    // Runs before the tool is consumed, so a rejected upgrade costs nothing.
    SpellCastResult CheckCast()
    {
        // GetHitItem() is only populated during effect handling; in CheckCast
        // the explicitly-targeted item is the one the player clicked.
        Player* player = GetCaster() ? GetCaster()->ToPlayer() : nullptr;
        Item* item = GetExplTargetItem();
        if (!player || !item)
            return SPELL_FAILED_BAD_TARGETS;

        if (!IsEnabled())
        {
            Say(player, "Item upgrades are currently disabled.");
            return SPELL_FAILED_DONT_REPORT;
        }

        uint8 target = TargetLevel();
        if (player->GetLevel() < target)
        {
            Say(player, Acore::StringFormat(
                "You must be level {} to use this.", target));
            return SPELL_FAILED_DONT_REPORT;
        }

        auto [baseEntry, step] = Decode(item->GetEntry());
        uint32 newEntry = 0;
        ItemTemplate const* proto = FindVariantAtLevel(baseEntry, target, newEntry);
        if (!proto)
        {
            Say(player, Acore::StringFormat(
                "{} has no reforged form at level {} or below.",
                item->GetTemplate()->Name1, target));
            return SPELL_FAILED_DONT_REPORT;
        }

        if (proto->RequiredLevel <= item->GetTemplate()->RequiredLevel)
        {
            Say(player, "That item is already at least this powerful.");
            return SPELL_FAILED_DONT_REPORT;
        }

        if (item->IsInTrade())
            return SPELL_FAILED_ITEM_NOT_READY;

        // A replacement arrives at full durability, so upgrading a broken item
        // would be a cut-price repair.
        if (item->GetTemplate()->MaxDurability > 0 &&
            item->GetUInt32Value(ITEM_FIELD_DURABILITY) == 0)
        {
            Say(player, "Repair that item before reforging it.");
            return SPELL_FAILED_DONT_REPORT;
        }

        return SPELL_CAST_OK;
    }

    void HandleUpgrade(SpellEffIndex /*effIndex*/)
    {
        Player* player = GetCaster() ? GetCaster()->ToPlayer() : nullptr;
        Item* item = GetHitItem();
        if (!player || !item)
            return;

        auto [baseEntry, step] = Decode(item->GetEntry());
        uint32 newEntry = 0;
        ItemTemplate const* proto = FindVariantAtLevel(baseEntry, TargetLevel(), newEntry);
        if (!proto)
            return;

        if (item->IsEquipped())
        {
            // Deferred to the next tick -- see UpgradeEquippedEvent for why the
            // equip cannot happen while this spell is still being cast.  Keyed
            // by GUID rather than by pointer or slot, both of which a tick can
            // invalidate.
            player->m_Events.AddEvent(
                new UpgradeEquippedEvent(player, item->GetGUID(), newEntry),
                player->m_Events.CalculateTime(1));
            return;
        }

        std::string oldName = item->GetTemplate()->Name1;
        if (UpgradeInBag(player, item, newEntry, proto))
            Say(player, Acore::StringFormat("{} reforged to level {}.",
                                            oldName, proto->RequiredLevel));
    }

    void Register() override
    {
        OnCheckCast += SpellCheckCastFn(spell_item_upgrade_tool::CheckCast);
        OnEffectHitTarget += SpellEffectFn(spell_item_upgrade_tool::HandleUpgrade,
                                           EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
    }
};

void AddSC_item_upgrade_tool()
{
    RegisterSpellScript(spell_item_upgrade_tool);
}
