/*
 * Copyright (C) 2016+ AzerothCore <www.azerothcore.org>, released under GNU AGPL v3 license: https://github.com/azerothcore/azerothcore-wotlk/blob/master/LICENSE-AGPL3
 */

// From SC
void AddMyPlayerScripts();
void AddSC_spell_bloomstrike();
void AddSC_aura_proc_self_hot_only();
void AddSC_aura_proc_moonfire_only();
void AddSC_spell_swiftmend_trigger();
void AddSC_spell_tree_of_life_ap();
void AddSC_PushbackImmunity();
void AddSC_mod_lifebloom();
void AddSC_spell_natures_focus_wrath();
void AddSC_bear_mangle_rage();
void AddSC_spell_no_swing_reset_arakkoa();
void AddSC_spell_mage_mage_armor_custom();
void AddSC_molten_armor_mechanic();
void AddSC_spell_mage_aegis_of_antonidas();
void AddSC_spell_mage_shattered_barrier_cooldown_reset();
void AddSC_frost_ice_armor_enhanced();
void AddSC_glacier_armor();
void AddSC_arcane_fortitude_mana_shield();
void AddSC_magic_absorption();
void AddSC_magic_attunement();
void AddSC_arcane_stability_mechanic();
void AddSC_fire_leech_mechanic();
void AddSC_firebreak_mechanic();
void AddSC_molten_shields_fire_ward();
void AddSC_spark_of_alar();
void AddSC_spell_mage_ablative_armor();
void AddSC_permafrost_absorb();
void AddSC_ice_lance_heal_mechanic();
void AddSC_priest_aura_interaction();
void AddSC_mark_of_penitence();
void AddSC_spell_killing_word();
void AddSC_divine_aegis_damage_mechanic();
void AddSC_priest_refresh_dots();
void AddSC_unbreakable_will();
void AddSC_focused_power();
void AddSC_martyrdom();
void AddSC_gnosticism();
void AddSC_syncretism();
void AddSC_shadow_affinity();
void AddSC_dk_runic_power_mastery();
void AddSC_dk_improved_rune_tap();
void AddSC_dk_bloody_lesions();
void AddSC_dk_mark_of_blood_rework();
void AddSC_dk_will_of_necropolis_parry();
void AddSC_dk_presence_improvements();
void AddSC_dk_chillblains();
void AddSC_dk_hungering_cold_rework();
void AddSC_dk_epidemic_rework();
void AddSC_dk_magic_siphon();
void AddSC_dk_bone_shield_rework();
void AddSC_dk_grim_prophecy();
void AddSC_dk_crypt_fever_ebon_plague();
void AddSC_dk_pestilence_alonecraft();
void AddSC_dk_harvest_of_souls();
void AddSC_dk_master_of_ghouls_rework();
void AddSC_dk_hungry_dead();
void AddSC_dk_reanimated_sorceror();
void AddSC_dk_desecration_rework();
void AddSC_scaled_encounters_global();
void AddSC_scaled_encounters_icc();
void AddSC_scaled_encounters_ulduar();
void AddSC_scaled_encounters_naxx();
void AddSC_scaled_encounters_toc();
void AddSC_scaled_encounters_outland();
void AddSC_scaled_encounters_dungeons();
void AddSC_scaled_encounters_classic();
void AddSC_sha_focused_mind();
void AddSC_sha_ancestral_awakening_crit();
void AddSC_sha_purification();
void AddSC_sha_healing_focus();
void AddSC_sha_defence_of_nature();
void AddSC_sha_spiritsurge();
void AddSC_sha_tidal_waves();
void AddSC_sha_riptide_rework();
void AddSC_sha_healing_way();
void AddSC_sha_natures_guardian();
void AddSC_natures_guardian_pets();
void AddSC_spec_command();
void AddSC_trainer_gossip();
void AddSC_item_upgrade_tool();
void AddSC_item_upgrade_affix();
void AddSC_quartermaster();
void AddSC_warl_shard_on_proc();
void AddSC_warl_ruin();
void AddSC_warl_backlash();
void AddSC_warl_infernal_bargain();
void AddSC_warl_wailing_soul();
void AddSC_warl_sacrifice_the_weak();
void AddSC_warl_demonology();
void AddSC_warl_demon_pets();
void AddSC_warl_health_funnel_mana_feed();
void AddSC_warl_metamorphosis();
void AddSC_warl_fel_interdiction();
void AddSC_warl_drain_channeling();
void AddSC_rog_tricks_self();
void AddSC_rog_master_of_deception();
void AddSC_rog_dirty_tricks();
void AddSC_rog_hemorrhage();
void AddSC_rog_finishers();
void AddSC_rog_bladework();
void AddSC_war_riposte();
void AddSC_war_tactical_mastery();
void AddSC_war_improved_charge();
void AddSC_war_charge_in_combat();
void AddSC_war_intervene();
void AddSC_war_parry_conversions();
void AddSC_war_toughness();
void AddSC_war_prot_conversions();
void AddSC_war_incite();
void AddSC_war_blood_and_thunder();
void AddSC_war_improved_thunder_clap();
void AddSC_war_spellshield();
void AddSC_war_damage_shield();
void AddSC_war_barricade();
void AddSC_alonecraft_testlog();
void AddSC_flight_path_discovery();
void AddSC_hunter_pet_level_sync();
void AddSC_hunter_trap_launcher();
void AddSC_hunter_beast_cleave();
void AddSC_hunter_pack_hunting();
void AddSC_hunter_pet_tuning();
void AddSC_hunter_bm_pet();
void AddSC_hunter_bm_hunter();
void AddSC_hunter_mm_pet();
void AddSC_hunter_mm_hunter();
void AddSC_alonecraft_sim();

// Add all
// cf. the naming convention https://github.com/azerothcore/azerothcore-wotlk/blob/master/doc/changelog/master.md#how-to-upgrade-4
// additionally replace all '-' in the module folder name with '_' here
void Addworld_of_alonecraftScripts()
{
    AddSC_spell_mage_ablative_armor();
    AddMyPlayerScripts();
    AddSC_spell_bloomstrike();
    AddSC_aura_proc_self_hot_only();
    AddSC_aura_proc_moonfire_only();
    AddSC_spell_swiftmend_trigger();
    AddSC_spell_tree_of_life_ap();
    AddSC_PushbackImmunity();
    AddSC_mod_lifebloom();
    AddSC_spell_natures_focus_wrath();
    AddSC_bear_mangle_rage();
    AddSC_spell_no_swing_reset_arakkoa();
    AddSC_spell_mage_mage_armor_custom();
    AddSC_molten_armor_mechanic();
    AddSC_spell_mage_aegis_of_antonidas();
    AddSC_spell_mage_shattered_barrier_cooldown_reset();
    AddSC_frost_ice_armor_enhanced();
    AddSC_glacier_armor();
    AddSC_arcane_fortitude_mana_shield();
    AddSC_magic_absorption();
    AddSC_magic_attunement();
    AddSC_arcane_stability_mechanic();
    AddSC_fire_leech_mechanic();
    AddSC_firebreak_mechanic();
    AddSC_molten_shields_fire_ward();
    AddSC_spark_of_alar();
    AddSC_permafrost_absorb();
    AddSC_ice_lance_heal_mechanic();
    AddSC_priest_aura_interaction();
    AddSC_mark_of_penitence();
    AddSC_priest_refresh_dots();
    AddSC_spell_killing_word();
    AddSC_divine_aegis_damage_mechanic();
    AddSC_unbreakable_will();
    AddSC_focused_power();
    AddSC_martyrdom();
    AddSC_gnosticism();
    AddSC_syncretism();
    AddSC_shadow_affinity();
    AddSC_dk_runic_power_mastery();
    AddSC_dk_improved_rune_tap();
    AddSC_dk_bloody_lesions();
    AddSC_dk_mark_of_blood_rework();
    AddSC_dk_will_of_necropolis_parry();
    AddSC_dk_presence_improvements();
    AddSC_dk_chillblains();
    AddSC_dk_hungering_cold_rework();
    AddSC_dk_epidemic_rework();
    AddSC_dk_magic_siphon();
    AddSC_dk_bone_shield_rework();
    AddSC_dk_grim_prophecy();
    AddSC_dk_crypt_fever_ebon_plague();
    AddSC_dk_pestilence_alonecraft();
    AddSC_dk_harvest_of_souls();
    AddSC_dk_master_of_ghouls_rework();
    AddSC_dk_hungry_dead();
    AddSC_dk_reanimated_sorceror();
    AddSC_dk_desecration_rework();
    AddSC_scaled_encounters_global();
    AddSC_scaled_encounters_icc();
    AddSC_scaled_encounters_ulduar();
    AddSC_scaled_encounters_naxx();
    AddSC_scaled_encounters_toc();
    AddSC_scaled_encounters_outland();
    AddSC_scaled_encounters_dungeons();
    AddSC_scaled_encounters_classic();
    AddSC_sha_focused_mind();
    AddSC_sha_ancestral_awakening_crit();
    AddSC_sha_purification();
    AddSC_sha_healing_focus();
    AddSC_sha_defence_of_nature();
    AddSC_sha_spiritsurge();
    AddSC_sha_tidal_waves();
    AddSC_sha_riptide_rework();
    AddSC_sha_healing_way();
    AddSC_sha_natures_guardian();
    AddSC_natures_guardian_pets();
    AddSC_spec_command();
    AddSC_trainer_gossip();
    AddSC_item_upgrade_tool();
    AddSC_item_upgrade_affix();
    AddSC_quartermaster();
    AddSC_warl_shard_on_proc();
    AddSC_warl_ruin();
    AddSC_warl_backlash();
    AddSC_warl_infernal_bargain();
    AddSC_warl_wailing_soul();
    AddSC_warl_sacrifice_the_weak();
    AddSC_warl_demonology();
    AddSC_warl_demon_pets();
    AddSC_warl_health_funnel_mana_feed();
    AddSC_warl_metamorphosis();
    AddSC_warl_fel_interdiction();
    AddSC_warl_drain_channeling();
    AddSC_rog_tricks_self();
    AddSC_rog_master_of_deception();
    AddSC_rog_dirty_tricks();
    AddSC_rog_hemorrhage();
    AddSC_rog_finishers();
    AddSC_rog_bladework();
    AddSC_war_riposte();
    AddSC_war_tactical_mastery();
    AddSC_war_improved_charge();
    AddSC_war_charge_in_combat();
    AddSC_war_intervene();
    AddSC_war_parry_conversions();
    AddSC_war_toughness();
    AddSC_war_prot_conversions();
    AddSC_war_incite();
    AddSC_war_blood_and_thunder();
    AddSC_war_improved_thunder_clap();
    AddSC_war_spellshield();
    AddSC_war_damage_shield();
    AddSC_war_barricade();
    AddSC_alonecraft_testlog();
    AddSC_flight_path_discovery();
    AddSC_hunter_pet_level_sync();
    AddSC_hunter_trap_launcher();
    AddSC_hunter_beast_cleave();
    AddSC_hunter_pack_hunting();
    AddSC_hunter_pet_tuning();
    AddSC_hunter_bm_pet();
    AddSC_hunter_bm_hunter();
    AddSC_hunter_mm_pet();
    AddSC_hunter_mm_hunter();
    AddSC_alonecraft_sim();
}
