/*
 * Copyright (C) 2016+ AzerothCore <www.azerothcore.org>, released under GNU AGPL v3 license: https://github.com/azerothcore/azerothcore-wotlk/blob/master/LICENSE-AGPL3
 */

// From SC
void AddMyPlayerScripts();
void AddSC_spell_bloomstrike();
void AddSC_aura_proc_self_hot_only();
void AddSC_aura_proc_moonfire_only();
void AddSC_spell_swiftmend_trigger();
void AddSC_spell_tree_of_life_ap();
void AddSC_PushbackImmunity();
void AddSC_mod_lifebloom();
void AddSC_spell_natures_focus_wrath();
void AddSC_spell_no_swing_reset_arakkoa();
void AddSC_spell_mage_mage_armor_custom();
void AddSC_molten_armor_mechanic();
void AddSC_spell_mage_aegis_of_antonidas();
void AddSC_spell_mage_shattered_barrier_cooldown_reset();
void AddSC_frost_ice_armor_enhanced();
void AddSC_glacier_armor();
void AddSC_arcane_fortitude_mana_shield();
void AddSC_magic_absorption();
void AddSC_magic_attunement();
void AddSC_arcane_stability_mechanic();
void AddSC_fire_leech_mechanic();
void AddSC_firebreak_mechanic();
void AddSC_molten_shields_fire_ward();
void AddSC_spark_of_alar();
void AddSC_spell_mage_ablative_armor();
void AddSC_permafrost_absorb();
void AddSC_ice_lance_heal_mechanic();
void AddSC_priest_aura_interaction();
void AddSC_mark_of_penitence();
void AddSC_spell_killing_word();
void AddSC_divine_aegis_damage_mechanic();
void AddSC_priest_refresh_dots();
void AddSC_unbreakable_will();
void AddSC_focused_power();
void AddSC_martyrdom();
void AddSC_gnosticism();
void AddSC_syncretism();
void AddSC_shadow_affinity();
void AddSC_dk_runic_power_mastery();
void AddSC_dk_improved_rune_tap();
void AddSC_dk_bloody_lesions();
void AddSC_dk_mark_of_blood_rework();
void AddSC_dk_will_of_necropolis_parry();
void AddSC_dk_presence_improvements();
void AddSC_dk_chillblains();
void AddSC_dk_hungering_cold_rework();
void AddSC_dk_epidemic_rework();
void AddSC_dk_magic_siphon();
void AddSC_dk_bone_shield_rework();
void AddSC_dk_grim_prophecy();
void AddSC_dk_crypt_fever_ebon_plague();
void AddSC_dk_harvest_of_souls();
void AddSC_dk_master_of_ghouls_rework();
void AddSC_dk_hungry_dead();
void AddSC_dk_reanimated_sorceror();
void AddSC_dk_desecration_rework();
void AddSC_sha_focused_mind();
void AddSC_sha_ancestral_awakening_crit();
void AddSC_sha_purification();
void AddSC_sha_healing_focus();
void AddSC_sha_defence_of_nature();
void AddSC_sha_spiritsurge();
void AddSC_sha_tidal_waves();
void AddSC_sha_riptide_rework();

// Add all
// cf. the naming convention https://github.com/azerothcore/azerothcore-wotlk/blob/master/doc/changelog/master.md#how-to-upgrade-4
// additionally replace all '-' in the module folder name with '_' here
void Addworld_of_alonecraftScripts()
{
    AddSC_spell_mage_ablative_armor();
    AddMyPlayerScripts();
    AddSC_spell_bloomstrike();
    AddSC_aura_proc_self_hot_only();
    AddSC_aura_proc_moonfire_only();
    AddSC_spell_swiftmend_trigger();
    AddSC_spell_tree_of_life_ap();
    AddSC_PushbackImmunity();
    AddSC_mod_lifebloom();
    AddSC_spell_natures_focus_wrath();
    AddSC_spell_no_swing_reset_arakkoa();
    AddSC_spell_mage_mage_armor_custom();
    AddSC_molten_armor_mechanic();
    AddSC_spell_mage_aegis_of_antonidas();
    AddSC_spell_mage_shattered_barrier_cooldown_reset();
    AddSC_frost_ice_armor_enhanced();
    AddSC_glacier_armor();
    AddSC_arcane_fortitude_mana_shield();
    AddSC_magic_absorption();
    AddSC_magic_attunement();
    AddSC_arcane_stability_mechanic();
    AddSC_fire_leech_mechanic();
    AddSC_firebreak_mechanic();
    AddSC_molten_shields_fire_ward();
    AddSC_spark_of_alar();
    AddSC_permafrost_absorb();
    AddSC_ice_lance_heal_mechanic();
    AddSC_priest_aura_interaction();
    AddSC_mark_of_penitence();
    AddSC_priest_refresh_dots();
    AddSC_spell_killing_word();
    AddSC_divine_aegis_damage_mechanic();
    AddSC_unbreakable_will();
    AddSC_focused_power();
    AddSC_martyrdom();
    AddSC_gnosticism();
    AddSC_syncretism();
    AddSC_shadow_affinity();
    AddSC_dk_runic_power_mastery();
    AddSC_dk_improved_rune_tap();
    AddSC_dk_bloody_lesions();
    AddSC_dk_mark_of_blood_rework();
    AddSC_dk_will_of_necropolis_parry();
    AddSC_dk_presence_improvements();
    AddSC_dk_chillblains();
    AddSC_dk_hungering_cold_rework();
    AddSC_dk_epidemic_rework();
    AddSC_dk_magic_siphon();
    AddSC_dk_bone_shield_rework();
    AddSC_dk_grim_prophecy();
    AddSC_dk_crypt_fever_ebon_plague();
    AddSC_dk_harvest_of_souls();
    AddSC_dk_master_of_ghouls_rework();
    AddSC_dk_hungry_dead();
    AddSC_dk_reanimated_sorceror();
    AddSC_dk_desecration_rework();
    AddSC_sha_focused_mind();
    AddSC_sha_ancestral_awakening_crit();
    AddSC_sha_purification();
    AddSC_sha_healing_focus();
    AddSC_sha_defence_of_nature();
    AddSC_sha_spiritsurge();
    AddSC_sha_tidal_waves();
    AddSC_sha_riptide_rework();
}
