/*
 * The Quartermaster — level-up gear mail.
 *
 * Alonecraft runs 10x XP but leaves loot and gold rates at 1x, so a character
 * levels roughly ten times faster than equipment arrives and simply outruns
 * their gear.  On each level-up the Quartermaster mails three items, each in a
 * DIFFERENT equipment slot, chosen for the player's class and active spec.
 *
 * Everything expensive happens offline.  tools/gen_quartermaster_pool.py scores
 * every upgrade variant (entry >= 1000000, generated by gen_item_variants.py)
 * for each class/talent-tree/level/slot and writes the top few into
 * `alonecraft_quartermaster_pool`.  All that is left here is a weighted random
 * pick from an in-memory copy of that table.
 *
 * THE AFFIX IS PART OF THE ANSWER, not a runtime roll.  A vanilla green's whole
 * identity is often its affix -- "of the Eagle" is a caster item and "of the
 * Bear" is a tank item off the SAME base cloak -- so the generator picks the
 * affix that suits the archetype and stores the concrete id in `rand_prop`.
 * This file just applies it.  Item::CreateItem never rolls one on its own.
 *
 *   rand_prop = 0   fixed-stat item
 *             > 0   ItemRandomProperties.ID
 *             < 0   -ItemRandomSuffix.ID  (rescales off the item's own ItemLevel)
 *
 * Two things here are load-bearing and easy to get wrong:
 *
 *   1. The pool is keyed by TALENT TREE, not by spec slot.  GetActiveSpec()
 *      returns a slot index 0..7 (Alonecraft.ExtraSpec.MaxSpecs), which says
 *      nothing about what the spec IS -- it is a save-file number.  The tree
 *      has to be read from that slot's talents; see GetActiveTree below.
 *
 *   2. Picks are made per SLOT GROUP, not per InventoryType.  Choosing three
 *      distinct InventoryTypes would cheerfully mail a two-hander and a
 *      main-hand sword, or a chest and a robe -- the same body slot twice.
 *
 * The feature starts at level 10 (Alonecraft.Quartermaster.MinLevel) because
 * the level-5 variant tier is only 32 items across 4 slots; half the classes
 * cannot fill three distinct slots from it at all.  See the conf file.
 */

#include "CharacterCache.h"
#include "Chat.h"
#include "CommandScript.h"
#include "Config.h"
#include "DBCStores.h"
#include "DatabaseEnv.h"
#include "Item.h"
#include "Log.h"
#include "Mail.h"
#include "MultiSpec.h"
#include "ObjectAccessor.h"
#include "ObjectMgr.h"
#include "Player.h"
#include "Random.h"
#include "ScriptMgr.h"
#include "StringFormat.h"

#include <algorithm>
#include <sstream>
#include <unordered_map>
#include <unordered_set>
#include <vector>

using namespace Acore::ChatCommands;

namespace
{
    // ---------------------------------------------------------------------
    // Config
    // ---------------------------------------------------------------------

    bool Enabled()      { return sConfigMgr->GetOption<bool>("Alonecraft.Quartermaster.Enable", true); }
    bool IncludeBots()  { return sConfigMgr->GetOption<bool>("Alonecraft.Quartermaster.IncludeBots", false); }
    bool TierOnly()     { return sConfigMgr->GetOption<bool>("Alonecraft.Quartermaster.OnlyOnTierChange", false); }
    uint8 MinLevel()    { return sConfigMgr->GetOption<uint32>("Alonecraft.Quartermaster.MinLevel", 10); }
    uint8 MaxLevel()    { return sConfigMgr->GetOption<uint32>("Alonecraft.Quartermaster.MaxLevel", 80); }
    uint8 MaxQBand()    { return sConfigMgr->GetOption<uint32>("Alonecraft.Quartermaster.MaxQualityBand", 0); }
    uint32 SenderEntry(){ return sConfigMgr->GetOption<uint32>("Alonecraft.Quartermaster.SenderEntry", 200012); }

    uint8 ItemsPerLevel()
    {
        uint32 n = sConfigMgr->GetOption<uint32>("Alonecraft.Quartermaster.ItemsPerLevel", 3);
        return uint8(std::min<uint32>(n, MAX_MAIL_ITEMS));
    }

    uint8 MaxLevelsPerEvent()
    {
        uint32 n = sConfigMgr->GetOption<uint32>("Alonecraft.Quartermaster.MaxLevelsPerEvent", 3);
        return uint8(std::max<uint32>(1, n));
    }

    // ---------------------------------------------------------------------
    // Slot groups
    // ---------------------------------------------------------------------

    constexpr uint8 SG_NONE = 0xFF;

    // InventoryType -> equipment slot group.  Must stay in step with
    // SLOT_GROUP in tools/gen_quartermaster_pool.py; the generator's
    // --validate asserts every level tier offers at least three of these.
    uint8 SlotGroupOf(uint8 inv)
    {
        switch (inv)
        {
            case 1:  return 0;                      // head
            case 2:  return 1;                      // neck
            case 3:  return 2;                      // shoulders
            case 5:  case 20: return 3;             // chest, robe
            case 6:  return 4;                      // waist
            case 7:  return 5;                      // legs
            case 8:  return 6;                      // feet
            case 9:  return 7;                      // wrists
            case 10: return 8;                      // hands
            case 11: return 9;                      // finger
            case 12: return 10;                     // trinket
            case 16: return 11;                     // back
            case 13: case 17: case 21: return 12;   // one-hand, two-hand, main-hand
            case 14: case 22: case 23: return 13;   // off-hand, shield, held
            case 15: case 25: case 26: return 14;   // ranged, thrown, ranged-right
            default: return SG_NONE;
        }
    }

    // ---------------------------------------------------------------------
    // Pool cache
    // ---------------------------------------------------------------------

    struct PoolEntry
    {
        uint32 entry;
        int32  randProp;
        uint16 weight;
        uint8  qband;
    };

    // cls(4) | tree(2) | level(7) | inv(5) -- 18 bits.
    constexpr uint32 BucketKey(uint8 cls, uint8 tree, uint8 lvl, uint8 inv)
    {
        return (uint32(cls) << 14) | (uint32(tree) << 12) | (uint32(lvl) << 5) | inv;
    }

    constexpr uint32 TierKey(uint8 cls, uint8 tree, uint8 lvl)
    {
        return (uint32(cls) << 9) | (uint32(tree) << 7) | lvl;
    }

    struct TierSlots
    {
        std::vector<uint8> groups;                                  // distinct slot groups
        std::unordered_map<uint8, std::vector<uint8>> invByGroup;   // group -> InventoryTypes
    };

    std::unordered_map<uint32, std::vector<PoolEntry>> g_pool;
    std::unordered_map<uint32, TierSlots> g_tiers;

    // Characters backfilled since startup.  See HandleBackfillCommand for why
    // the mail-table check cannot stand on its own.
    std::unordered_set<ObjectGuid::LowType> g_backfilled;

    void LoadPool()
    {
        g_pool.clear();
        g_tiers.clear();

        // Ordered so each bucket's vector is band 0 first, then band 1, each
        // rank-ascending.  The runtime band filter is therefore a prefix.
        QueryResult r = WorldDatabase.Query(
            "SELECT class_id, tree, req_level, inv_type, qband, entry, rand_prop, weight "
            "FROM alonecraft_quartermaster_pool "
            "ORDER BY class_id, tree, req_level, inv_type, qband, `rank`");

        if (!r)
        {
            LOG_ERROR("server.loading",
                      ">> Quartermaster: alonecraft_quartermaster_pool is empty or missing. "
                      "Run tools/gen_quartermaster_pool.py and apply its SQL.");
            return;
        }

        uint32 stale = 0;
        do
        {
            Field* f = r->Fetch();
            uint8  cls   = f[0].Get<uint8>();
            uint8  tree  = f[1].Get<uint8>();
            uint8  lvl   = f[2].Get<uint8>();
            uint8  inv   = f[3].Get<uint8>();
            uint8  qband = f[4].Get<uint8>();
            uint32 entry = f[5].Get<uint32>();

            // A pool generated before the last variant regeneration would point
            // at entries that no longer exist.  Drop them and report the count
            // rather than mailing a null item at level-up.
            if (!sObjectMgr->GetItemTemplate(entry))
            {
                ++stale;
                continue;
            }

            uint8 group = SlotGroupOf(inv);
            if (group == SG_NONE)
                continue;

            g_pool[BucketKey(cls, tree, lvl, inv)].push_back(
                { entry, f[6].Get<int32>(), f[7].Get<uint16>(), qband });

            TierSlots& tier = g_tiers[TierKey(cls, tree, lvl)];
            std::vector<uint8>& invs = tier.invByGroup[group];
            if (invs.empty())
                tier.groups.push_back(group);
            if (std::find(invs.begin(), invs.end(), inv) == invs.end())
                invs.push_back(inv);
        } while (r->NextRow());

        uint32 entries = 0;
        for (auto const& [key, vec] : g_pool)
            entries += uint32(vec.size());

        LOG_INFO("server.loading",
                 ">> Loaded {} quartermaster pool entries in {} buckets ({} stale skipped)",
                 entries, g_pool.size(), stale);
    }

    // ---------------------------------------------------------------------
    // Selection
    // ---------------------------------------------------------------------

    // The dominant tree of a talent distribution, or the class's conventional
    // solo levelling tree when nothing has been spent yet.
    //
    // The fallback is also the weakest point of the whole feature: between
    // levels 10 and 20 a character has only a handful of points, so the argmax
    // is noisy and a Holy-levelling paladin will be sent Retribution gear for a
    // while.  That is accepted, not a bug -- the archetypes barely diverge at
    // those levels.
    uint8 TreeFromPoints(uint8 cls, uint8 const (&points)[3])
    {
        uint8 best = 0;
        for (uint8 i = 1; i < 3; ++i)
            if (points[i] > points[best])
                best = i;

        if (points[best])
            return best;

        switch (cls)
        {
            case CLASS_WARRIOR:      return 0;  // Arms
            case CLASS_PALADIN:      return 2;  // Retribution
            case CLASS_HUNTER:       return 0;  // Beast Mastery
            case CLASS_ROGUE:        return 1;  // Combat
            case CLASS_PRIEST:       return 2;  // Shadow
            case CLASS_DEATH_KNIGHT: return 0;  // Blood
            case CLASS_SHAMAN:       return 1;  // Enhancement
            case CLASS_MAGE:         return 2;  // Frost
            case CLASS_WARLOCK:      return 0;  // Affliction
            case CLASS_DRUID:        return 1;  // Feral
            default:                 return 0;
        }
    }

    // The tree a character is actually playing, read from the ACTIVE spec slot.
    uint8 GetActiveTree(Player* player)
    {
        uint8 points[3] = {};
        Alonecraft::GetTalentTreePointsForSpec(player, player->GetActiveSpec(), points);
        return TreeFromPoints(player->getClass(), points);
    }

    // Same answer for a character who is not logged in.
    //
    // GetTalentTreePointsForSpec needs a Player, so this walks the DB rows
    // instead: character_talent holds (spell, specMask) and specMask is the
    // same 1 << specSlot that Aura::IsInSpec tests.  Talent.dbc has no
    // spell -> talent index, so the store is scanned once; that is fine for an
    // admin command and keeps the answer identical to the online path rather
    // than approximating it.
    uint8 GetActiveTreeOffline(ObjectGuid::LowType guid, uint8 cls)
    {
        uint8 activeSpec = 0;
        if (QueryResult r = CharacterDatabase.Query(
                "SELECT activeTalentGroup FROM characters WHERE guid = {}", guid))
            activeSpec = r->Fetch()[0].Get<uint8>();

        std::unordered_map<uint32, uint8> spells;   // spell -> specMask
        if (QueryResult r = CharacterDatabase.Query(
                "SELECT spell, specMask FROM character_talent WHERE guid = {}", guid))
            do
            {
                Field* f = r->Fetch();
                spells[f[0].Get<uint32>()] = f[1].Get<uint8>();
            } while (r->NextRow());

        uint8 points[3] = {};
        for (uint32 i = 0; i < sTalentStore.GetNumRows(); ++i)
        {
            TalentEntry const* talent = sTalentStore.LookupEntry(i);
            if (!talent)
                continue;

            TalentTabEntry const* tab = sTalentTabStore.LookupEntry(talent->TalentTab);
            if (!tab || tab->tabpage >= 3)
                continue;

            for (uint8 rank = 0; rank < MAX_TALENT_RANK; ++rank)
            {
                if (!talent->RankID[rank])
                    continue;

                auto it = spells.find(talent->RankID[rank]);
                if (it != spells.end() && (it->second & (1 << activeSpec)))
                {
                    points[tab->tabpage] += uint8(rank + 1);
                    break;
                }
            }
        }

        return TreeFromPoints(cls, points);
    }

    // Everything mailed must be equippable on arrival, so round the tier DOWN.
    // Rounding up would mail a level-34 character gear they cannot wear for
    // another level.  The cost is gear up to 4 levels stale, which the churn of
    // three items per level hides.
    uint8 TierFor(uint8 level)
    {
        return std::min<uint8>(80, std::max<uint8>(5, (level / 5) * 5));
    }

    struct Pick
    {
        uint32 entry;
        int32  randProp;
    };

    // Entries in a bucket usable under the configured quality band.  Because
    // the query ordered by qband, these are always a prefix.
    uint32 EligibleCount(std::vector<PoolEntry> const& entries, uint8 maxBand)
    {
        uint32 n = 0;
        while (n < entries.size() && entries[n].qband <= maxBand)
            ++n;
        return n;
    }

    std::vector<Pick> PickItems(uint8 cls, uint8 tree, uint8 level)
    {
        std::vector<Pick> picks;

        uint8 tier = TierFor(level);
        uint8 maxBand = MaxQBand();
        uint8 want = ItemsPerLevel();

        auto tierIt = g_tiers.find(TierKey(cls, tree, tier));
        if (tierIt == g_tiers.end())
            return picks;

        TierSlots const& slots = tierIt->second;

        // Partial Fisher-Yates: shuffling guarantees distinct slot groups
        // without rejection sampling, so there is no loop that can spin when a
        // tier is thin.
        std::vector<uint8> groups = slots.groups;
        for (size_t i = 0; i + 1 < groups.size() && i < want; ++i)
            std::swap(groups[i], groups[urand(uint32(i), uint32(groups.size() - 1))]);

        for (uint8 group : groups)
        {
            if (picks.size() >= want)
                break;

            // Weight each InventoryType by how many items it actually offers,
            // so the main-hand group does not favour two-handers merely for
            // being one of its three types.
            std::vector<std::pair<uint8, uint32>> viable;
            uint32 total = 0;
            for (uint8 inv : slots.invByGroup.at(group))
            {
                auto it = g_pool.find(BucketKey(cls, tree, tier, inv));
                if (it == g_pool.end())
                    continue;
                uint32 n = EligibleCount(it->second, maxBand);
                if (!n)
                    continue;
                viable.emplace_back(inv, n);
                total += n;
            }

            // Empty after the band filter -- rare, but this is the reroll path:
            // drop the group and move to the next shuffled one.
            if (viable.empty())
                continue;

            uint32 roll = urand(0, total - 1);
            uint8 inv = viable.back().first;
            for (auto const& [candidate, n] : viable)
            {
                if (roll < n)
                {
                    inv = candidate;
                    break;
                }
                roll -= n;
            }

            std::vector<PoolEntry> const& bucket = g_pool[BucketKey(cls, tree, tier, inv)];
            uint32 count = EligibleCount(bucket, maxBand);

            uint32 weightSum = 0;
            for (uint32 i = 0; i < count; ++i)
                weightSum += bucket[i].weight;
            if (!weightSum)
                continue;

            uint32 wroll = urand(0, weightSum - 1);
            PoolEntry const* chosen = &bucket[count - 1];
            for (uint32 i = 0; i < count; ++i)
            {
                if (wroll < bucket[i].weight)
                {
                    chosen = &bucket[i];
                    break;
                }
                wroll -= bucket[i].weight;
            }

            picks.push_back({ chosen->entry, chosen->randProp });
        }

        return picks;
    }

    // ---------------------------------------------------------------------
    // Sending
    // ---------------------------------------------------------------------

    // Who a shipment is for.  Kept separate from Player so the same code path
    // serves a level-up (online) and a backfill (usually offline) -- the
    // alternative, writing item_instance and mail rows by hand for the offline
    // case, would duplicate the affix serialisation and fail silently when it
    // drifted.
    struct Recipient
    {
        ObjectGuid::LowType guid;
        uint8  cls;
        uint8  tree;
        Player* online;   // may be nullptr
    };

    Recipient RecipientOf(Player* player)
    {
        return { player->GetGUID().GetCounter(), player->getClass(),
                 GetActiveTree(player), player };
    }

    bool SendShipment(Recipient const& who, uint8 level)
    {
        std::vector<Pick> picks = PickItems(who.cls, who.tree, level);
        if (picks.empty())
            return false;

        CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();

        // MAIL_CREATURE puts the entry in the mail row and the client resolves
        // the name and portrait with CMSG_CREATURE_QUERY, which is answered
        // from creature_template alone -- so the sender needs no spawn.  Same
        // arrangement as The Postmaster in Player::SendItemRetrievalMail.
        MailSender sender(MAIL_CREATURE, SenderEntry());
        MailDraft draft(
            // ASCII only.  The 3.3.5a client does not decode UTF-8 for enUS, so
            // a typographic dash here reaches the mailbox as three garbage
            // bytes.  Same for every other player-visible string in this file.
            Acore::StringFormat("Requisition - Level {}", level),
            "Your service is noted.$B$BEnclosed is equipment drawn against your "
            "rank and calling. Requisitions are issued on promotion; see that "
            "you make use of them.$B$B- The Quartermaster");

        for (Pick const& pick : picks)
        {
            Item* item = Item::CreateItem(pick.entry, 1);
            if (!item)
                continue;

            // Before SaveToDB, always: SetItemRandomProperties writes
            // ITEM_FIELD_RANDOM_PROPERTIES_ID and the PROP_ENCHANTMENT_SLOT_*
            // enchantments that SaveToDB is about to persist.  Safe on an
            // unowned item -- its SetState(ITEM_CHANGED, GetOwner()) passes a
            // null player, which SetState guards.
            if (pick.randProp)
                item->SetItemRandomProperties(pick.randProp);

            item->SaveToDB(trans);
            draft.AddItem(item);
        }

        // The two-argument form delivers to an online player without a relog;
        // the guid-only form is the offline path.
        if (who.online)
            draft.SendMailTo(trans, MailReceiver(who.online, who.guid), sender);
        else
            draft.SendMailTo(trans, MailReceiver(who.guid), sender);

        CharacterDatabase.CommitTransaction(trans);
        return true;
    }

    std::string ItemLink(Pick const& pick)
    {
        ItemTemplate const* proto = sObjectMgr->GetItemTemplate(pick.entry);
        if (!proto)
            return "(missing item)";

        std::stringstream s;
        s << "|c" << std::hex << ItemQualityColors[proto->Quality] << std::dec
          << "|Hitem:" << proto->ItemId << ":0:0:0:0:0:" << pick.randProp
          << ":0:0|h[" << proto->Name1 << "]|h|r";
        return s.str();
    }
}

// -------------------------------------------------------------------------
// Scripts
// -------------------------------------------------------------------------

class woa_quartermaster_world : public WorldScript
{
public:
    woa_quartermaster_world() : WorldScript("woa_quartermaster_world", { WORLDHOOK_ON_STARTUP }) { }

    // OnStartup, not OnAfterConfigLoad: the latter runs before the world
    // database is loaded, so the query would come back empty.  Same reasoning
    // as ItemUpgradeAffix.cpp.
    void OnStartup() override
    {
        LoadPool();
    }
};

class woa_quartermaster_player : public PlayerScript
{
public:
    woa_quartermaster_player() : PlayerScript("woa_quartermaster_player", { PLAYERHOOK_ON_LEVEL_CHANGED }) { }

    void OnPlayerLevelChanged(Player* player, uint8 oldLevel) override
    {
        if (!Enabled() || !player || !player->GetSession())
            return;

        // mod-playerbots constructs its sessions with is_bot = true.  Hundreds
        // of bots levelling would write 3 item_instance + 1 mail + 3 mail_items
        // rows each, per level, forever, for mail no bot will ever open.
        if (player->GetSession()->IsBot() && !IncludeBots())
            return;

        uint8 newLevel = player->GetLevel();
        if (newLevel <= oldLevel)   // .levelup downwards
            return;

        uint8 first = std::max<uint8>(uint8(oldLevel + 1), MinLevel());
        uint8 last  = std::min<uint8>(newLevel, MaxLevel());
        if (first > last)
            return;

        // Player::GiveXP calls GiveLevel one level at a time, so a multi-level
        // XP gain already arrives here as separate events.  The only caller
        // that jumps is the GM command, and ".levelup 79" should not produce 79
        // mails.  Clamp to the TOP of the jump: gear for where you landed.
        uint8 cap = MaxLevelsPerEvent();
        if (uint16(last - first + 1) > cap)
            first = uint8(last - cap + 1);

        Recipient who = RecipientOf(player);
        for (uint8 level = first; level <= last; ++level)
        {
            if (TierOnly() && level % 5 != 0)
                continue;
            SendShipment(who, level);
        }
    }
};

class woa_quartermaster_commandscript : public CommandScript
{
public:
    woa_quartermaster_commandscript() : CommandScript("woa_quartermaster_commandscript") { }

    ChatCommandTable GetCommands() const override
    {
        static ChatCommandTable qmCommandTable =
        {
            { "reload",   HandleReloadCommand,   SEC_ADMINISTRATOR, Console::Yes },
            { "backfill", HandleBackfillCommand, SEC_ADMINISTRATOR, Console::Yes },
            { "peek",     HandlePeekCommand,     SEC_GAMEMASTER,    Console::No  },
            { "test",     HandleTestCommand,     SEC_GAMEMASTER,    Console::No  },
        };

        static ChatCommandTable commandTable =
        {
            { "quartermaster", qmCommandTable },
        };

        return commandTable;
    }

    static bool HandleReloadCommand(ChatHandler* handler)
    {
        LoadPool();
        handler->PSendSysMessage("Quartermaster pool reloaded.");
        return true;
    }

    // Dry run: shows what a shipment WOULD contain and mails nothing.  This is
    // the fastest way to confirm spec detection and spec targeting are both
    // working -- a tank and a caster peeking the same tier should differ in
    // both the items and their affixes.
    static bool HandlePeekCommand(ChatHandler* handler, Optional<uint8> levelArg)
    {
        Player* player = handler->GetSession()->GetPlayer();
        if (!player)
            return false;

        uint8 level = levelArg.value_or(player->GetLevel());
        uint8 points[3] = {};
        Alonecraft::GetTalentTreePointsForSpec(player, player->GetActiveSpec(), points);

        handler->PSendSysMessage("Quartermaster: spec slot {}, talents {}/{}/{}, tree {}, tier {}.",
            player->GetActiveSpec() + 1, points[0], points[1], points[2],
            GetActiveTree(player), TierFor(level));

        std::vector<Pick> picks = PickItems(player->getClass(), GetActiveTree(player), level);
        if (picks.empty())
        {
            handler->PSendSysMessage("  (nothing - pool empty for this class/tree/tier)");
            return true;
        }

        for (Pick const& pick : picks)
            handler->PSendSysMessage("  {}", ItemLink(pick));
        return true;
    }

    static bool HandleTestCommand(ChatHandler* handler, Optional<uint8> levelArg)
    {
        Player* player = handler->GetSession()->GetPlayer();
        if (!player)
            return false;

        uint8 level = levelArg.value_or(player->GetLevel());
        if (!SendShipment(RecipientOf(player), level))
        {
            handler->PSendSysMessage("Quartermaster: nothing to send for level {}.", level);
            return true;
        }

        handler->PSendSysMessage("Quartermaster: shipment for level {} sent.", level);
        return true;
    }

    // .quartermaster backfill <name> [force]
    //
    // The feature is stateless: nothing records which shipments a character has
    // already had, because a login-time write and a progress table are more
    // failure surface than the one edge case they cover.  The exception is
    // turning the Quartermaster on for a realm that already has characters --
    // they would otherwise stay un-geared until their next level.  This is that
    // one-off, and it works on offline characters so nobody has to log in.
    static bool HandleBackfillCommand(ChatHandler* handler, std::string const& name,
                                      Optional<std::string> forceArg)
    {
        CharacterCacheEntry const* cache = sCharacterCache->GetCharacterCacheByName(name);
        if (!cache)
        {
            handler->PSendSysMessage("Quartermaster: no character named '{}'.", name);
            return true;
        }

        ObjectGuid::LowType guid = cache->Guid.GetCounter();
        bool force = forceArg && *forceArg == "force";

        // Backfilling twice silently doubles every shipment, and afterwards
        // there is no way to tell the copies apart.  Refuse by default.
        //
        // TWO checks, because the DB one alone is not enough: MailDraft writes
        // through a transaction on the async queue, so a second invocation
        // moments after the first reads a mail table that does not yet contain
        // the first run's rows.  That is not hypothetical -- it is exactly how
        // this command double-mailed its first real target.  g_backfilled
        // closes that window; the query covers restarts, where the set is empty.
        if (!force)
        {
            if (g_backfilled.count(guid))
            {
                handler->PSendSysMessage(
                    "Quartermaster: {} was already backfilled since startup. "
                    "Re-run with 'force' to send anyway.", cache->Name);
                return true;
            }

            if (QueryResult r = CharacterDatabase.Query(
                    "SELECT COUNT(*) FROM mail WHERE receiver = {} AND sender = {}",
                    guid, SenderEntry()))
            {
                uint32 existing = r->Fetch()[0].Get<uint32>();
                if (existing)
                {
                    handler->PSendSysMessage(
                        "Quartermaster: {} already has {} shipment(s). Re-run with "
                        "'force' to send anyway.", cache->Name, existing);
                    return true;
                }
            }
        }

        g_backfilled.insert(guid);

        Player* online = ObjectAccessor::FindPlayerByLowGUID(guid);
        uint8 tree = online ? GetActiveTree(online) : GetActiveTreeOffline(guid, cache->Class);
        Recipient who{ guid, cache->Class, tree, online };

        uint8 first = MinLevel();
        uint8 last = std::min<uint8>(cache->Level, MaxLevel());
        if (first > last)
        {
            handler->PSendSysMessage("Quartermaster: {} is level {}, below MinLevel {}.",
                cache->Name, cache->Level, first);
            return true;
        }

        // MaxLevelsPerEvent deliberately does NOT apply here.  It exists to stop
        // ".character level X 80" producing 70 mails as a side effect; a
        // backfill is someone asking for exactly that.
        uint32 sent = 0;
        for (uint8 level = first; level <= last; ++level)
        {
            if (TierOnly() && level % 5 != 0)
                continue;
            if (SendShipment(who, level))
                ++sent;
        }

        handler->PSendSysMessage(
            "Quartermaster: backfilled {} shipment(s) for {} (class {}, tree {}, levels {}-{}){}.",
            sent, cache->Name, cache->Class, tree, first, last,
            online ? "" : " - offline, will appear at next login");
        return true;
    }
};

void AddSC_quartermaster()
{
    new woa_quartermaster_world();
    new woa_quartermaster_player();
    new woa_quartermaster_commandscript();
}
