#include "AlonecraftTestLog.h"
#include "Player.h"
#include "ScriptMgr.h"
#include "SpellAuraEffects.h"
#include "SpellMgr.h"
#include "SpellScript.h"
#include "SpellScriptLoader.h"
#include "Unit.h"

// Improved Charge (redesigned) -- Warrior Arms talent
// Ranks: 12285 / 12697 -- woa_2026_08_07_12.sql
//
// TODO.md: "Improved Charge (0, 1): Increases the amount of rage generated by
//  your Charge ability by 10. Killing an enemy has a 50/100% chance to reset
//  the cooldown on Charge. (2 ranks)"
//
// Handled by DBC:
//   The rage bonus (effect 0, ADD_FLAT_MODIFIER, +10 rage at both ranks), the
//   PROC_FLAG_KILL trigger and the 50/100% chance, which the proc system rolls
//   from ProcChance before this script is ever reached.
//
// Handled here:
//   The reset itself, because 3.3.5 has no SPELL_EFFECT_RESET_COOLDOWN -- it
//   is a Cataclysm effect.  Every stock cooldown reset is a script; this
//   follows Readiness (spell_hunter.cpp:698-712), which is the closest
//   precedent because it too has to clear both kinds of cooldown.
//
// The category clear is the load-bearing line.  Charge has RecoveryTime 0 and
// CategoryRecoveryTime 15000 under category 1219 -- the whole 15 seconds is a
// *category* cooldown, so RemoveSpellCooldown alone would appear to do nothing.
// The category is read off the spell rather than hardcoded as 1219.

enum ImprovedChargeSpells
{
    SPELL_WARRIOR_CHARGE_R1 = 100,
    SPELL_WARRIOR_CHARGE_R2 = 6178,
    SPELL_WARRIOR_CHARGE_R3 = 11578,
};

static constexpr uint32 CHARGE_RANKS[] =
{
    SPELL_WARRIOR_CHARGE_R1,
    SPELL_WARRIOR_CHARGE_R2,
    SPELL_WARRIOR_CHARGE_R3,
};

class spell_warr_improved_charge : public AuraScript
{
    PrepareAuraScript(spell_warr_improved_charge);

    void HandleProc(AuraEffect const* /*aurEff*/, ProcEventInfo& /*eventInfo*/)
    {
        PreventDefaultAction();

        Player* player = GetTarget() ? GetTarget()->ToPlayer() : nullptr;
        if (!player)
            return;

        for (uint32 chargeId : CHARGE_RANKS)
            if (player->HasSpell(chargeId))
                player->RemoveSpellCooldown(chargeId, true);

        // All three ranks share category 1219; clearing it once is enough, and
        // this is what actually makes Charge usable again.
        if (SpellInfo const* charge = sSpellMgr->GetSpellInfo(SPELL_WARRIOR_CHARGE_R1))
            if (uint32 category = charge->GetCategory())
                player->RemoveCategoryCooldown(category);

        ACTEST("WAR.IMPCHARGE", "kill reset talent={} category={}",
            GetId(), sSpellMgr->GetSpellInfo(SPELL_WARRIOR_CHARGE_R1)->GetCategory());
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_warr_improved_charge::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

class spell_warr_improved_charge_loader : public SpellScriptLoader
{
public:
    spell_warr_improved_charge_loader() : SpellScriptLoader("spell_warr_improved_charge") { }

    AuraScript* GetAuraScript() const override
    {
        return new spell_warr_improved_charge();
    }
};

void AddSC_war_improved_charge()
{
    new spell_warr_improved_charge_loader();
}
